// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apitypes

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiTokenScopes        = "ApiToken.Scopes"
	BearerAuthScopes      = "BearerAuth.Scopes"
	IntegrationHmacScopes = "IntegrationHmac.Scopes"
)

// Defines values for AuthResultTokenType.
const (
	Bearer AuthResultTokenType = "Bearer"
)

// Defines values for BillingPeriod.
const (
	Monthly BillingPeriod = "monthly"
	Yearly  BillingPeriod = "yearly"
)

// Defines values for BillingPlan.
const (
	Free    BillingPlan = "free"
	Premium BillingPlan = "premium"
)

// Defines values for ComponentStatus.
const (
	ComponentStatusDegradedPerformance ComponentStatus = "degraded_performance"
	ComponentStatusMajorOutage         ComponentStatus = "major_outage"
	ComponentStatusOperational         ComponentStatus = "operational"
	ComponentStatusPartialOutage       ComponentStatus = "partial_outage"
	ComponentStatusUnderMaintenance    ComponentStatus = "under_maintenance"
)

// Defines values for ImportMode.
const (
	Skip   ImportMode = "skip"
	Update ImportMode = "update"
)

// Defines values for ImportRegion.
const (
	Eu ImportRegion = "eu"
	Us ImportRegion = "us"
)

// Defines values for ImportSource.
const (
	Instatus   ImportSource = "instatus"
	Statusmate ImportSource = "statusmate"
	Statuspage ImportSource = "statuspage"
	Statuspal  ImportSource = "statuspal"
)

// Defines values for ImportStatus.
const (
	ImportStatusCompleted ImportStatus = "completed"
	ImportStatusFailed    ImportStatus = "failed"
	ImportStatusPending   ImportStatus = "pending"
	ImportStatusRunning   ImportStatus = "running"
)

// Defines values for IncidentImpact.
const (
	Critical IncidentImpact = "critical"
	Major    IncidentImpact = "major"
	Minor    IncidentImpact = "minor"
	None     IncidentImpact = "none"
)

// Defines values for IncidentStatus.
const (
	Identified    IncidentStatus = "identified"
	Investigating IncidentStatus = "investigating"
	Monitoring    IncidentStatus = "monitoring"
	Resolved      IncidentStatus = "resolved"
)

// Defines values for MaintenanceStatus.
const (
	MaintenanceStatusCompleted  MaintenanceStatus = "completed"
	MaintenanceStatusInProgress MaintenanceStatus = "in_progress"
	MaintenanceStatusScheduled  MaintenanceStatus = "scheduled"
)

// Defines values for OverallStatus.
const (
	OverallStatusDegradedPerformance OverallStatus = "degraded_performance"
	OverallStatusMajorOutage         OverallStatus = "major_outage"
	OverallStatusOperational         OverallStatus = "operational"
	OverallStatusPartialOutage       OverallStatus = "partial_outage"
	OverallStatusUnderMaintenance    OverallStatus = "under_maintenance"
)

// Defines values for PaymentProvider.
const (
	Cloudpayments PaymentProvider = "cloudpayments"
	Robokassa     PaymentProvider = "robokassa"
	Tinkoff       PaymentProvider = "tinkoff"
	Yookassa      PaymentProvider = "yookassa"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusRefunded  PaymentStatus = "refunded"
	PaymentStatusSucceeded PaymentStatus = "succeeded"
)

// Defines values for StatusPageVisibility.
const (
	StatusPageVisibilityPrivate StatusPageVisibility = "private"
	StatusPageVisibilityPublic  StatusPageVisibility = "public"
)

// Defines values for StatusPageCreateVisibility.
const (
	StatusPageCreateVisibilityPrivate StatusPageCreateVisibility = "private"
	StatusPageCreateVisibilityPublic  StatusPageCreateVisibility = "public"
)

// Defines values for StatusPageUpdateVisibility.
const (
	Private StatusPageUpdateVisibility = "private"
	Public  StatusPageUpdateVisibility = "public"
)

// Defines values for SubscriberChannel.
const (
	Email    SubscriberChannel = "email"
	Ical     SubscriberChannel = "ical"
	Max      SubscriberChannel = "max"
	Rss      SubscriberChannel = "rss"
	Slack    SubscriberChannel = "slack"
	Telegram SubscriberChannel = "telegram"
	Webhook  SubscriberChannel = "webhook"
)

// Defines values for SubscriberScope.
const (
	SubscriberScopeComponents SubscriberScope = "components"
	SubscriberScopePage       SubscriberScope = "page"
)

// Defines values for SubscriptionStatus.
const (
	SubscriptionStatusActive   SubscriptionStatus = "active"
	SubscriptionStatusCanceled SubscriptionStatus = "canceled"
	SubscriptionStatusPastDue  SubscriptionStatus = "past_due"
	SubscriptionStatusPending  SubscriptionStatus = "pending"
)

// AuthResult defines model for AuthResult.
type AuthResult struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn TTL access-токена в секундах
	ExpiresIn    int                 `json:"expires_in"`
	RefreshToken *string             `json:"refresh_token"`
	TokenType    AuthResultTokenType `json:"token_type"`
	User         AuthUser            `json:"user"`
}

// AuthResultTokenType defines model for AuthResult.TokenType.
type AuthResultTokenType string

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email  openapi_types.Email `json:"email"`
	Id     openapi_types.UUID  `json:"id"`
	Locale *string             `json:"locale,omitempty"`
	Name   *string             `json:"name,omitempty"`
}

// BillingPeriod defines model for BillingPeriod.
type BillingPeriod string

// BillingPlan defines model for BillingPlan.
type BillingPlan string

// CheckoutRequest defines model for CheckoutRequest.
type CheckoutRequest struct {
	BillingPeriod BillingPeriod `json:"billing_period"`
	Plan          BillingPlan   `json:"plan"`
}

// CheckoutResponse defines model for CheckoutResponse.
type CheckoutResponse struct {
	// ConfirmationUrl URL для редиректа/виджета оплаты на стороне провайдера
	ConfirmationUrl *string            `json:"confirmation_url,omitempty"`
	PaymentId       openapi_types.UUID `json:"payment_id"`
	Provider        *PaymentProvider   `json:"provider,omitempty"`
}

// Component defines model for Component.
type Component struct {
	CreatedAt     *time.Time          `json:"created_at,omitempty"`
	CurrentStatus ComponentStatus     `json:"current_status"`
	Description   *string             `json:"description"`
	DisplayState  *bool               `json:"display_state,omitempty"`
	GroupId       *openapi_types.UUID `json:"group_id"`
	Id            openapi_types.UUID  `json:"id"`
	IsPrivate     *bool               `json:"is_private,omitempty"`
	Name          string              `json:"name"`
	ParentId      *openapi_types.UUID `json:"parent_id"`
	Position      int                 `json:"position"`
	ShowUptime    *bool               `json:"show_uptime,omitempty"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`
}

// ComponentCreate defines model for ComponentCreate.
type ComponentCreate struct {
	CurrentStatus *ComponentStatus    `json:"current_status,omitempty"`
	Description   *string             `json:"description,omitempty"`
	DisplayState  *bool               `json:"display_state,omitempty"`
	GroupId       *openapi_types.UUID `json:"group_id,omitempty"`
	IsPrivate     *bool               `json:"is_private,omitempty"`
	Name          string              `json:"name"`
	ParentId      *openapi_types.UUID `json:"parent_id,omitempty"`
	Position      *int                `json:"position,omitempty"`
	ShowUptime    *bool               `json:"show_uptime,omitempty"`
	StatusPageId  *openapi_types.UUID `json:"status_page_id,omitempty"`
}

// ComponentGroup defines model for ComponentGroup.
type ComponentGroup struct {
	AggregatedStatus *ComponentStatus   `json:"aggregated_status,omitempty"`
	Components       *[]Component       `json:"components,omitempty"`
	Id               openapi_types.UUID `json:"id"`
	Name             string             `json:"name"`
	Position         int                `json:"position"`
}

// ComponentGroupCreate defines model for ComponentGroupCreate.
type ComponentGroupCreate struct {
	Name     string `json:"name"`
	Position *int   `json:"position,omitempty"`
}

// ComponentGroupUpdate defines model for ComponentGroupUpdate.
type ComponentGroupUpdate struct {
	Name     *string `json:"name,omitempty"`
	Position *int    `json:"position,omitempty"`
}

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus string

// ComponentUpdate defines model for ComponentUpdate.
type ComponentUpdate struct {
	CurrentStatus *ComponentStatus    `json:"current_status,omitempty"`
	Description   *string             `json:"description,omitempty"`
	DisplayState  *bool               `json:"display_state,omitempty"`
	GroupId       *openapi_types.UUID `json:"group_id"`
	IsPrivate     *bool               `json:"is_private,omitempty"`
	Name          *string             `json:"name,omitempty"`
	Position      *int                `json:"position,omitempty"`
	ShowUptime    *bool               `json:"show_uptime,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// ImportJob defines model for ImportJob.
type ImportJob struct {
	CreatedAt  *time.Time         `json:"created_at,omitempty"`
	FinishedAt *time.Time         `json:"finished_at"`
	Id         openapi_types.UUID `json:"id"`
	Region     *ImportRegion      `json:"region,omitempty"`

	// Report Итог: что перенесено/пропущено/ошибки
	Report *map[string]interface{} `json:"report,omitempty"`
	Source ImportSource            `json:"source"`
	Status ImportStatus            `json:"status"`
}

// ImportMode defines model for ImportMode.
type ImportMode string

// ImportRegion defines model for ImportRegion.
type ImportRegion string

// ImportRequest defines model for ImportRequest.
type ImportRequest struct {
	// ApiKey API-ключ источника; не хранится дольше задачи
	ApiKey string        `json:"api_key"`
	Mode   *ImportMode   `json:"mode,omitempty"`
	Region *ImportRegion `json:"region,omitempty"`
	Source ImportSource  `json:"source"`

	// Subdomain Идентификатор страницы в системе-источнике
	Subdomain string `json:"subdomain"`
}

// ImportSource defines model for ImportSource.
type ImportSource string

// ImportStatus defines model for ImportStatus.
type ImportStatus string

// Incident defines model for Incident.
type Incident struct {
	Components    *[]IncidentComponent `json:"components,omitempty"`
	CurrentStatus IncidentStatus       `json:"current_status"`
	Id            openapi_types.UUID   `json:"id"`
	Impact        IncidentImpact       `json:"impact"`
	IsVisible     *bool                `json:"is_visible,omitempty"`
	Postmortem    *string              `json:"postmortem"`
	ResolvedAt    *time.Time           `json:"resolved_at"`
	StartedAt     time.Time            `json:"started_at"`
	Title         string               `json:"title"`
	Updates       *[]IncidentUpdate    `json:"updates,omitempty"`
}

// IncidentComponent defines model for IncidentComponent.
type IncidentComponent struct {
	ComponentId               openapi_types.UUID `json:"component_id"`
	ComponentStatusInIncident ComponentStatus    `json:"component_status_in_incident"`
}

// IncidentCreate defines model for IncidentCreate.
type IncidentCreate struct {
	// Body Текст первого обновления
	Body       string               `json:"body"`
	Components *[]IncidentComponent `json:"components,omitempty"`
	Impact     IncidentImpact       `json:"impact"`
	Notify     *bool                `json:"notify,omitempty"`
	StartedAt  *time.Time           `json:"started_at,omitempty"`
	Status     IncidentStatus       `json:"status"`

	// StatusPageId Страница, к которой относится инцидент
	StatusPageId openapi_types.UUID `json:"status_page_id"`
	Title        string             `json:"title"`
}

// IncidentImpact defines model for IncidentImpact.
type IncidentImpact string

// IncidentList defines model for IncidentList.
type IncidentList struct {
	Items      *[]Incident `json:"items,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// IncidentPatch defines model for IncidentPatch.
type IncidentPatch struct {
	Components *[]IncidentComponent `json:"components,omitempty"`
	Impact     *IncidentImpact      `json:"impact,omitempty"`
	IsVisible  *bool                `json:"is_visible,omitempty"`
	Postmortem *string              `json:"postmortem,omitempty"`
	Title      *string              `json:"title,omitempty"`
}

// IncidentStatus defines model for IncidentStatus.
type IncidentStatus string

// IncidentUpdate defines model for IncidentUpdate.
type IncidentUpdate struct {
	// Body Текст обновления (Markdown)
	Body              string             `json:"body"`
	CreatedAt         time.Time          `json:"created_at"`
	Id                openapi_types.UUID `json:"id"`
	NotifySubscribers *bool              `json:"notify_subscribers,omitempty"`
	Status            IncidentStatus     `json:"status"`
}

// IncidentUpdateCreate defines model for IncidentUpdateCreate.
type IncidentUpdateCreate struct {
	Body   string         `json:"body"`
	Notify *bool          `json:"notify,omitempty"`
	Status IncidentStatus `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Maintenance defines model for Maintenance.
type Maintenance struct {
	CompletedAt    *time.Time            `json:"completed_at"`
	ComponentIds   *[]openapi_types.UUID `json:"component_ids,omitempty"`
	Description    *string               `json:"description"`
	Id             openapi_types.UUID    `json:"id"`
	ScheduledEnd   time.Time             `json:"scheduled_end"`
	ScheduledStart time.Time             `json:"scheduled_start"`
	StartedAt      *time.Time            `json:"started_at"`
	Status         MaintenanceStatus     `json:"status"`
	Title          string                `json:"title"`
	Updates        *[]MaintenanceUpdate  `json:"updates,omitempty"`
}

// MaintenanceCreate defines model for MaintenanceCreate.
type MaintenanceCreate struct {
	ComponentIds   *[]openapi_types.UUID `json:"component_ids,omitempty"`
	Description    *string               `json:"description,omitempty"`
	Notify         *bool                 `json:"notify,omitempty"`
	ScheduledEnd   time.Time             `json:"scheduled_end"`
	ScheduledStart time.Time             `json:"scheduled_start"`
	Title          string                `json:"title"`
}

// MaintenanceList defines model for MaintenanceList.
type MaintenanceList struct {
	Items      *[]Maintenance `json:"items,omitempty"`
	Pagination *Pagination    `json:"pagination,omitempty"`
}

// MaintenancePatch defines model for MaintenancePatch.
type MaintenancePatch struct {
	ComponentIds   *[]openapi_types.UUID `json:"component_ids,omitempty"`
	Description    *string               `json:"description,omitempty"`
	ScheduledEnd   *time.Time            `json:"scheduled_end,omitempty"`
	ScheduledStart *time.Time            `json:"scheduled_start,omitempty"`
	Status         *MaintenanceStatus    `json:"status,omitempty"`
	Title          *string               `json:"title,omitempty"`
}

// MaintenanceStatus defines model for MaintenanceStatus.
type MaintenanceStatus string

// MaintenanceUpdate defines model for MaintenanceUpdate.
type MaintenanceUpdate struct {
	Body              string             `json:"body"`
	CreatedAt         time.Time          `json:"created_at"`
	Id                openapi_types.UUID `json:"id"`
	NotifySubscribers *bool              `json:"notify_subscribers,omitempty"`
}

// MaintenanceUpdateCreate defines model for MaintenanceUpdateCreate.
type MaintenanceUpdateCreate struct {
	Body   string `json:"body"`
	Notify *bool  `json:"notify,omitempty"`
}

// OverallStatus defines model for OverallStatus.
type OverallStatus string

// PageSummary defines model for PageSummary.
type PageSummary struct {
	ActiveIncidents     *[]Incident      `json:"active_incidents,omitempty"`
	ActiveMaintenances  *[]Maintenance   `json:"active_maintenances,omitempty"`
	Groups              []ComponentGroup `json:"groups"`
	OverallStatus       OverallStatus    `json:"overall_status"`
	UngroupedComponents *[]Component     `json:"ungrouped_components,omitempty"`
	UpdatedAt           *time.Time       `json:"updated_at,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page    *int `json:"page,omitempty"`
	PerPage *int `json:"per_page,omitempty"`
	Total   *int `json:"total,omitempty"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount            float32            `json:"amount"`
	CreatedAt         *time.Time         `json:"created_at,omitempty"`
	Currency          string             `json:"currency"`
	Id                openapi_types.UUID `json:"id"`
	PaidAt            *time.Time         `json:"paid_at"`
	Provider          *PaymentProvider   `json:"provider,omitempty"`
	ProviderPaymentId *string            `json:"provider_payment_id"`

	// ReceiptId Ссылка на фискальный чек ОФД
	ReceiptId *string       `json:"receipt_id"`
	Status    PaymentStatus `json:"status"`
}

// PaymentProvider defines model for PaymentProvider.
type PaymentProvider string

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	AccountName *string             `json:"account_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Locale      *string             `json:"locale,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Password    string              `json:"password"`
}

// StatusPage defines model for StatusPage.
type StatusPage struct {
	AccountId      *openapi_types.UUID     `json:"account_id,omitempty"`
	CreatedAt      *time.Time              `json:"created_at,omitempty"`
	CustomDomain   *string                 `json:"custom_domain"`
	DefaultLocale  *string                 `json:"default_locale,omitempty"`
	Description    *string                 `json:"description,omitempty"`
	DomainVerified *bool                   `json:"domain_verified,omitempty"`
	FaviconUrl     *string                 `json:"favicon_url"`
	HidePoweredBy  *bool                   `json:"hide_powered_by,omitempty"`
	Id             openapi_types.UUID      `json:"id"`
	LogoUrl        *string                 `json:"logo_url"`
	Name           string                  `json:"name"`
	RedirectUrl    *string                 `json:"redirect_url"`
	Slug           string                  `json:"slug"`
	Theme          *map[string]interface{} `json:"theme,omitempty"`
	Timezone       *string                 `json:"timezone,omitempty"`
	UpdatedAt      *time.Time              `json:"updated_at,omitempty"`
	Visibility     StatusPageVisibility    `json:"visibility"`
}

// StatusPageVisibility defines model for StatusPage.Visibility.
type StatusPageVisibility string

// StatusPageCreate defines model for StatusPageCreate.
type StatusPageCreate struct {
	DefaultLocale *string                     `json:"default_locale,omitempty"`
	Description   *string                     `json:"description,omitempty"`
	Name          string                      `json:"name"`
	Slug          string                      `json:"slug"`
	Timezone      *string                     `json:"timezone,omitempty"`
	Visibility    *StatusPageCreateVisibility `json:"visibility,omitempty"`
}

// StatusPageCreateVisibility defines model for StatusPageCreate.Visibility.
type StatusPageCreateVisibility string

// StatusPageUpdate defines model for StatusPageUpdate.
type StatusPageUpdate struct {
	DefaultLocale *string                     `json:"default_locale,omitempty"`
	Description   *string                     `json:"description,omitempty"`
	FaviconUrl    *string                     `json:"favicon_url"`
	HidePoweredBy *bool                       `json:"hide_powered_by,omitempty"`
	LogoUrl       *string                     `json:"logo_url"`
	Name          *string                     `json:"name,omitempty"`
	RedirectUrl   *string                     `json:"redirect_url"`
	Theme         *map[string]interface{}     `json:"theme,omitempty"`
	Timezone      *string                     `json:"timezone,omitempty"`
	Visibility    *StatusPageUpdateVisibility `json:"visibility,omitempty"`
}

// StatusPageUpdateVisibility defines model for StatusPageUpdate.Visibility.
type StatusPageUpdateVisibility string

// SubscribeRequest defines model for SubscribeRequest.
type SubscribeRequest struct {
	Address      string                `json:"address"`
	Channel      SubscriberChannel     `json:"channel"`
	ComponentIds *[]openapi_types.UUID `json:"component_ids,omitempty"`
	Scope        *SubscriberScope      `json:"scope,omitempty"`
}

// Subscriber defines model for Subscriber.
type Subscriber struct {
	// Address email | telegram chat_id | webhook url
	Address      string                `json:"address"`
	Channel      SubscriberChannel     `json:"channel"`
	ComponentIds *[]openapi_types.UUID `json:"component_ids,omitempty"`
	Confirmed    bool                  `json:"confirmed"`
	CreatedAt    *time.Time            `json:"created_at,omitempty"`
	Id           openapi_types.UUID    `json:"id"`
	Scope        SubscriberScope       `json:"scope"`
}

// SubscriberChannel defines model for SubscriberChannel.
type SubscriberChannel string

// SubscriberCreate defines model for SubscriberCreate.
type SubscriberCreate struct {
	Address      string                `json:"address"`
	Channel      SubscriberChannel     `json:"channel"`
	ComponentIds *[]openapi_types.UUID `json:"component_ids,omitempty"`
	Scope        *SubscriberScope      `json:"scope,omitempty"`
}

// SubscriberScope defines model for SubscriberScope.
type SubscriberScope string

// Subscription defines model for Subscription.
type Subscription struct {
	BillingPeriod      *BillingPeriod     `json:"billing_period,omitempty"`
	CancelAtPeriodEnd  *bool              `json:"cancel_at_period_end,omitempty"`
	CurrentPeriodEnd   *time.Time         `json:"current_period_end"`
	CurrentPeriodStart *time.Time         `json:"current_period_start"`
	Id                 openapi_types.UUID `json:"id"`
	Plan               BillingPlan        `json:"plan"`
	Provider           *PaymentProvider   `json:"provider,omitempty"`
	Status             SubscriptionStatus `json:"status"`
}

// SubscriptionStatus defines model for SubscriptionStatus.
type SubscriptionStatus string

// TokenCreate defines model for TokenCreate.
type TokenCreate struct {
	Name   string    `json:"name"`
	Scopes *[]string `json:"scopes,omitempty"`
}

// TokenCreated defines model for TokenCreated.
type TokenCreated struct {
	Id     openapi_types.UUID `json:"id"`
	Name   string             `json:"name"`
	Scopes *[]string          `json:"scopes,omitempty"`

	// Token Показывается единожды
	Token string `json:"token"`
}

// UptimeReport defines model for UptimeReport.
type UptimeReport struct {
	ComponentId openapi_types.UUID `json:"component_id"`
	Daily       *[]struct {
		Date          *openapi_types.Date `json:"date,omitempty"`
		UptimePercent *float32            `json:"uptime_percent,omitempty"`
	} `json:"daily,omitempty"`
	Days          int     `json:"days"`
	UptimePercent float32 `json:"uptime_percent"`
}

// IdPath defines model for IdPath.
type IdPath = openapi_types.UUID

// IntegrationId defines model for IntegrationId.
type IntegrationId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PerPage defines model for PerPage.
type PerPage = int

// Slug defines model for Slug.
type Slug = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// GetBillingPaymentsParams defines parameters for GetBillingPayments.
type GetBillingPaymentsParams struct {
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// PostBillingWebhookProviderJSONBody defines parameters for PostBillingWebhookProvider.
type PostBillingWebhookProviderJSONBody map[string]interface{}

// GetComponentsParams defines parameters for GetComponents.
type GetComponentsParams struct {
	// StatusPageId Страница, чьи компоненты вернуть. Обязателен при операторском JWT; при ApiToken выводится из токена.
	StatusPageId *openapi_types.UUID `form:"status_page_id,omitempty" json:"status_page_id,omitempty"`
}

// PostIntegrationsIntegrationIdGenericJSONBody defines parameters for PostIntegrationsIntegrationIdGeneric.
type PostIntegrationsIntegrationIdGenericJSONBody map[string]interface{}

// PostIntegrationsIntegrationIdGrafanaJSONBody defines parameters for PostIntegrationsIntegrationIdGrafana.
type PostIntegrationsIntegrationIdGrafanaJSONBody map[string]interface{}

// PostIntegrationsIntegrationIdPagerdutyJSONBody defines parameters for PostIntegrationsIntegrationIdPagerduty.
type PostIntegrationsIntegrationIdPagerdutyJSONBody map[string]interface{}

// PostIntegrationsIntegrationIdPrometheusJSONBody defines parameters for PostIntegrationsIntegrationIdPrometheus.
type PostIntegrationsIntegrationIdPrometheusJSONBody map[string]interface{}

// GetPagesSlugIncidentsParams defines parameters for GetPagesSlugIncidents.
type GetPagesSlugIncidentsParams struct {
	Status      *IncidentStatus     `form:"status,omitempty" json:"status,omitempty"`
	Impact      *IncidentImpact     `form:"impact,omitempty" json:"impact,omitempty"`
	ComponentId *openapi_types.UUID `form:"component_id,omitempty" json:"component_id,omitempty"`
	Page        *Page               `form:"page,omitempty" json:"page,omitempty"`
	PerPage     *PerPage            `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetPagesSlugMaintenancesParams defines parameters for GetPagesSlugMaintenances.
type GetPagesSlugMaintenancesParams struct {
	Status  *MaintenanceStatus `form:"status,omitempty" json:"status,omitempty"`
	Page    *Page              `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage           `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetPagesSlugUptimeParams defines parameters for GetPagesSlugUptime.
type GetPagesSlugUptimeParams struct {
	ComponentId openapi_types.UUID `form:"component_id" json:"component_id"`
	Days        *int               `form:"days,omitempty" json:"days,omitempty"`
}

// GetSubscribeConfirmParams defines parameters for GetSubscribeConfirm.
type GetSubscribeConfirmParams struct {
	Token string `form:"token" json:"token"`
}

// GetSubscribeSlackCallbackParams defines parameters for GetSubscribeSlackCallback.
type GetSubscribeSlackCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// GetSubscribersParams defines parameters for GetSubscribers.
type GetSubscribersParams struct {
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetUnsubscribeParams defines parameters for GetUnsubscribe.
type GetUnsubscribeParams struct {
	Token string `form:"token" json:"token"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthLogoutJSONRequestBody defines body for PostAuthLogout for application/json ContentType.
type PostAuthLogoutJSONRequestBody = RefreshRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostBillingCheckoutJSONRequestBody defines body for PostBillingCheckout for application/json ContentType.
type PostBillingCheckoutJSONRequestBody = CheckoutRequest

// PostBillingWebhookProviderJSONRequestBody defines body for PostBillingWebhookProvider for application/json ContentType.
type PostBillingWebhookProviderJSONRequestBody PostBillingWebhookProviderJSONBody

// PatchComponentGroupsIdJSONRequestBody defines body for PatchComponentGroupsId for application/json ContentType.
type PatchComponentGroupsIdJSONRequestBody = ComponentGroupUpdate

// PostComponentsJSONRequestBody defines body for PostComponents for application/json ContentType.
type PostComponentsJSONRequestBody = ComponentCreate

// PatchComponentsIdJSONRequestBody defines body for PatchComponentsId for application/json ContentType.
type PatchComponentsIdJSONRequestBody = ComponentUpdate

// PostImportJSONRequestBody defines body for PostImport for application/json ContentType.
type PostImportJSONRequestBody = ImportRequest

// PostIncidentsJSONRequestBody defines body for PostIncidents for application/json ContentType.
type PostIncidentsJSONRequestBody = IncidentCreate

// PatchIncidentsIdJSONRequestBody defines body for PatchIncidentsId for application/json ContentType.
type PatchIncidentsIdJSONRequestBody = IncidentPatch

// PostIncidentsIdUpdatesJSONRequestBody defines body for PostIncidentsIdUpdates for application/json ContentType.
type PostIncidentsIdUpdatesJSONRequestBody = IncidentUpdateCreate

// PostIntegrationsIntegrationIdGenericJSONRequestBody defines body for PostIntegrationsIntegrationIdGeneric for application/json ContentType.
type PostIntegrationsIntegrationIdGenericJSONRequestBody PostIntegrationsIntegrationIdGenericJSONBody

// PostIntegrationsIntegrationIdGrafanaJSONRequestBody defines body for PostIntegrationsIntegrationIdGrafana for application/json ContentType.
type PostIntegrationsIntegrationIdGrafanaJSONRequestBody PostIntegrationsIntegrationIdGrafanaJSONBody

// PostIntegrationsIntegrationIdPagerdutyJSONRequestBody defines body for PostIntegrationsIntegrationIdPagerduty for application/json ContentType.
type PostIntegrationsIntegrationIdPagerdutyJSONRequestBody PostIntegrationsIntegrationIdPagerdutyJSONBody

// PostIntegrationsIntegrationIdPrometheusJSONRequestBody defines body for PostIntegrationsIntegrationIdPrometheus for application/json ContentType.
type PostIntegrationsIntegrationIdPrometheusJSONRequestBody PostIntegrationsIntegrationIdPrometheusJSONBody

// PostMaintenancesJSONRequestBody defines body for PostMaintenances for application/json ContentType.
type PostMaintenancesJSONRequestBody = MaintenanceCreate

// PatchMaintenancesIdJSONRequestBody defines body for PatchMaintenancesId for application/json ContentType.
type PatchMaintenancesIdJSONRequestBody = MaintenancePatch

// PostMaintenancesIdUpdatesJSONRequestBody defines body for PostMaintenancesIdUpdates for application/json ContentType.
type PostMaintenancesIdUpdatesJSONRequestBody = MaintenanceUpdateCreate

// PostPagesJSONRequestBody defines body for PostPages for application/json ContentType.
type PostPagesJSONRequestBody = StatusPageCreate

// PatchPagesIdJSONRequestBody defines body for PatchPagesId for application/json ContentType.
type PatchPagesIdJSONRequestBody = StatusPageUpdate

// PostPagesIdComponentGroupsJSONRequestBody defines body for PostPagesIdComponentGroups for application/json ContentType.
type PostPagesIdComponentGroupsJSONRequestBody = ComponentGroupCreate

// PostPagesSlugSubscribeJSONRequestBody defines body for PostPagesSlugSubscribe for application/json ContentType.
type PostPagesSlugSubscribeJSONRequestBody = SubscribeRequest

// PostSubscribersJSONRequestBody defines body for PostSubscribers for application/json ContentType.
type PostSubscribersJSONRequestBody = SubscriberCreate

// PostTokensJSONRequestBody defines body for PostTokens for application/json ContentType.
type PostTokensJSONRequestBody = TokenCreate
