// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, owner_user_id)
VALUES ($1, $2)
RETURNING id, name, billing_plan, owner_user_id, created_at, updated_at
`

type CreateAccountParams struct {
	Name        string
	OwnerUserID uuid.UUID
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.OwnerUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingPlan,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, billing_plan, owner_user_id, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingPlan,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByOwner = `-- name: GetAccountByOwner :one
SELECT id, name, billing_plan, owner_user_id, created_at, updated_at FROM accounts WHERE owner_user_id = $1 ORDER BY created_at LIMIT 1
`

func (q *Queries) GetAccountByOwner(ctx context.Context, ownerUserID uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByOwner, ownerUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingPlan,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
