// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (status_page_id, token_hash, name, scopes)
VALUES ($1, $2, $3, $4)
RETURNING id, status_page_id, token_hash, name, scopes, last_used_at, created_at, updated_at
`

type CreateAPITokenParams struct {
	StatusPageID uuid.UUID
	TokenHash    string
	Name         string
	Scopes       []string
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.StatusPageID,
		arg.TokenHash,
		arg.Name,
		arg.Scopes,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.TokenHash,
		&i.Name,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, status_page_id, token_hash, name, scopes, last_used_at, created_at, updated_at FROM api_tokens WHERE id = $1
`

func (q *Queries) GetAPIToken(ctx context.Context, id uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPIToken, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.TokenHash,
		&i.Name,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, status_page_id, token_hash, name, scopes, last_used_at, created_at, updated_at FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.TokenHash,
		&i.Name,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPITokensByPage = `-- name: ListAPITokensByPage :many
SELECT id, status_page_id, token_hash, name, scopes, last_used_at, created_at, updated_at FROM api_tokens
WHERE status_page_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByPage(ctx context.Context, statusPageID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensByPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.TokenHash,
			&i.Name,
			&i.Scopes,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
