// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    account_id, subscription_id, amount_minor, currency, status, provider,
    provider_payment_id, idempotency_key, billing_period
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, account_id, subscription_id, amount_minor, currency, status, provider, provider_payment_id, idempotency_key, receipt_id, billing_period, created_at, paid_at
`

type CreatePaymentParams struct {
	AccountID         uuid.UUID
	SubscriptionID    *uuid.UUID
	AmountMinor       int64
	Currency          string
	Status            string
	Provider          *string
	ProviderPaymentID *string
	IdempotencyKey    *string
	BillingPeriod     *string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.AccountID,
		arg.SubscriptionID,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.Provider,
		arg.ProviderPaymentID,
		arg.IdempotencyKey,
		arg.BillingPeriod,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SubscriptionID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.IdempotencyKey,
		&i.ReceiptID,
		&i.BillingPeriod,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const ensureSubscription = `-- name: EnsureSubscription :one
INSERT INTO subscriptions (account_id)
VALUES ($1)
ON CONFLICT (account_id) DO UPDATE SET account_id = subscriptions.account_id
RETURNING id, account_id, plan, status, billing_period, provider, provider_customer_token, trial_ends_at, current_period_start, current_period_end, cancel_at_period_end, dunning_attempts, created_at, updated_at
`

// Создаёт дефолтную free-подписку аккаунта, если её ещё нет; возвращает текущую.
func (q *Queries) EnsureSubscription(ctx context.Context, accountID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, ensureSubscription, accountID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Plan,
		&i.Status,
		&i.BillingPeriod,
		&i.Provider,
		&i.ProviderCustomerToken,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.DunningAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, account_id, subscription_id, amount_minor, currency, status, provider, provider_payment_id, idempotency_key, receipt_id, billing_period, created_at, paid_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SubscriptionID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.IdempotencyKey,
		&i.ReceiptID,
		&i.BillingPeriod,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getPaymentByProviderID = `-- name: GetPaymentByProviderID :one
SELECT id, account_id, subscription_id, amount_minor, currency, status, provider, provider_payment_id, idempotency_key, receipt_id, billing_period, created_at, paid_at FROM payments WHERE provider_payment_id = $1
`

func (q *Queries) GetPaymentByProviderID(ctx context.Context, providerPaymentID *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderID, providerPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SubscriptionID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.IdempotencyKey,
		&i.ReceiptID,
		&i.BillingPeriod,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getSubscriptionByAccount = `-- name: GetSubscriptionByAccount :one
SELECT id, account_id, plan, status, billing_period, provider, provider_customer_token, trial_ends_at, current_period_start, current_period_end, cancel_at_period_end, dunning_attempts, created_at, updated_at FROM subscriptions WHERE account_id = $1
`

func (q *Queries) GetSubscriptionByAccount(ctx context.Context, accountID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByAccount, accountID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Plan,
		&i.Status,
		&i.BillingPeriod,
		&i.Provider,
		&i.ProviderCustomerToken,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.DunningAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSubscriptions = `-- name: ListDueSubscriptions :many
SELECT id, account_id, plan, status, billing_period, provider, provider_customer_token, trial_ends_at, current_period_start, current_period_end, cancel_at_period_end, dunning_attempts, created_at, updated_at FROM subscriptions
WHERE plan = 'premium'
  AND status IN ('active', 'past_due')
  AND current_period_end IS NOT NULL
  AND current_period_end <= $1
ORDER BY current_period_end ASC
LIMIT $2
`

type ListDueSubscriptionsParams struct {
	CurrentPeriodEnd *time.Time
	Limit            int32
}

// Подписки, требующие внимания worker-billing: активные/просроченные premium с истёкшим
// текущим периодом (рекуррент или dunning/откат).
func (q *Queries) ListDueSubscriptions(ctx context.Context, arg ListDueSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listDueSubscriptions, arg.CurrentPeriodEnd, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Plan,
			&i.Status,
			&i.BillingPeriod,
			&i.Provider,
			&i.ProviderCustomerToken,
			&i.TrialEndsAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtPeriodEnd,
			&i.DunningAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByAccount = `-- name: ListPaymentsByAccount :many
SELECT id, account_id, subscription_id, amount_minor, currency, status, provider, provider_payment_id, idempotency_key, receipt_id, billing_period, created_at, paid_at FROM payments
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByAccountParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListPaymentsByAccount(ctx context.Context, arg ListPaymentsByAccountParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.SubscriptionID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.IdempotencyKey,
			&i.ReceiptID,
			&i.BillingPeriod,
			&i.CreatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountPlan = `-- name: SetAccountPlan :exec
UPDATE accounts SET billing_plan = $2 WHERE id = $1
`

type SetAccountPlanParams struct {
	ID          uuid.UUID
	BillingPlan BillingPlan
}

func (q *Queries) SetAccountPlan(ctx context.Context, arg SetAccountPlanParams) error {
	_, err := q.db.Exec(ctx, setAccountPlan, arg.ID, arg.BillingPlan)
	return err
}

const updatePaymentResult = `-- name: UpdatePaymentResult :one
UPDATE payments
SET status = $2,
    provider_payment_id = COALESCE($3, provider_payment_id),
    receipt_id = COALESCE($4, receipt_id),
    paid_at = $5
WHERE id = $1
RETURNING id, account_id, subscription_id, amount_minor, currency, status, provider, provider_payment_id, idempotency_key, receipt_id, billing_period, created_at, paid_at
`

type UpdatePaymentResultParams struct {
	ID                uuid.UUID
	Status            string
	ProviderPaymentID *string
	ReceiptID         *string
	PaidAt            *time.Time
}

func (q *Queries) UpdatePaymentResult(ctx context.Context, arg UpdatePaymentResultParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentResult,
		arg.ID,
		arg.Status,
		arg.ProviderPaymentID,
		arg.ReceiptID,
		arg.PaidAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SubscriptionID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.IdempotencyKey,
		&i.ReceiptID,
		&i.BillingPeriod,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET plan = $2,
    status = $3,
    billing_period = $4,
    provider = $5,
    provider_customer_token = $6,
    trial_ends_at = $7,
    current_period_start = $8,
    current_period_end = $9,
    cancel_at_period_end = $10,
    dunning_attempts = $11
WHERE account_id = $1
RETURNING id, account_id, plan, status, billing_period, provider, provider_customer_token, trial_ends_at, current_period_start, current_period_end, cancel_at_period_end, dunning_attempts, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	AccountID             uuid.UUID
	Plan                  BillingPlan
	Status                string
	BillingPeriod         *string
	Provider              *string
	ProviderCustomerToken *string
	TrialEndsAt           *time.Time
	CurrentPeriodStart    *time.Time
	CurrentPeriodEnd      *time.Time
	CancelAtPeriodEnd     bool
	DunningAttempts       int32
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.AccountID,
		arg.Plan,
		arg.Status,
		arg.BillingPeriod,
		arg.Provider,
		arg.ProviderCustomerToken,
		arg.TrialEndsAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.DunningAttempts,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Plan,
		&i.Status,
		&i.BillingPeriod,
		&i.Provider,
		&i.ProviderCustomerToken,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.DunningAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
