// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changelog.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChangelogEntry = `-- name: CreateChangelogEntry :one
INSERT INTO changelog_entries (status_page_id, title, body, published, published_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status_page_id, title, body, published, published_at, created_at, updated_at
`

type CreateChangelogEntryParams struct {
	StatusPageID uuid.UUID
	Title        string
	Body         string
	Published    bool
	PublishedAt  *time.Time
}

func (q *Queries) CreateChangelogEntry(ctx context.Context, arg CreateChangelogEntryParams) (ChangelogEntry, error) {
	row := q.db.QueryRow(ctx, createChangelogEntry,
		arg.StatusPageID,
		arg.Title,
		arg.Body,
		arg.Published,
		arg.PublishedAt,
	)
	var i ChangelogEntry
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.Body,
		&i.Published,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChangelogEntry = `-- name: DeleteChangelogEntry :exec
DELETE FROM changelog_entries WHERE id = $1
`

func (q *Queries) DeleteChangelogEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChangelogEntry, id)
	return err
}

const getChangelogEntry = `-- name: GetChangelogEntry :one
SELECT id, status_page_id, title, body, published, published_at, created_at, updated_at FROM changelog_entries WHERE id = $1
`

func (q *Queries) GetChangelogEntry(ctx context.Context, id uuid.UUID) (ChangelogEntry, error) {
	row := q.db.QueryRow(ctx, getChangelogEntry, id)
	var i ChangelogEntry
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.Body,
		&i.Published,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChangelogByPage = `-- name: ListChangelogByPage :many
SELECT id, status_page_id, title, body, published, published_at, created_at, updated_at FROM changelog_entries
WHERE status_page_id = $1
ORDER BY COALESCE(published_at, created_at) DESC, created_at DESC
`

// Админский список: все записи (включая черновики), новые сверху.
func (q *Queries) ListChangelogByPage(ctx context.Context, statusPageID uuid.UUID) ([]ChangelogEntry, error) {
	rows, err := q.db.Query(ctx, listChangelogByPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogEntry{}
	for rows.Next() {
		var i ChangelogEntry
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Title,
			&i.Body,
			&i.Published,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedChangelog = `-- name: ListPublishedChangelog :many
SELECT id, status_page_id, title, body, published, published_at, created_at, updated_at FROM changelog_entries
WHERE status_page_id = $1 AND published = true
ORDER BY published_at DESC NULLS LAST, created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublishedChangelogParams struct {
	StatusPageID uuid.UUID
	Limit        int32
	Offset       int32
}

// Публичный список: только опубликованные, новые сверху, с пагинацией.
func (q *Queries) ListPublishedChangelog(ctx context.Context, arg ListPublishedChangelogParams) ([]ChangelogEntry, error) {
	rows, err := q.db.Query(ctx, listPublishedChangelog, arg.StatusPageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogEntry{}
	for rows.Next() {
		var i ChangelogEntry
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Title,
			&i.Body,
			&i.Published,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChangelogEntry = `-- name: UpdateChangelogEntry :one
UPDATE changelog_entries
SET title = $2, body = $3, published = $4, published_at = $5
WHERE id = $1
RETURNING id, status_page_id, title, body, published, published_at, created_at, updated_at
`

type UpdateChangelogEntryParams struct {
	ID          uuid.UUID
	Title       string
	Body        string
	Published   bool
	PublishedAt *time.Time
}

func (q *Queries) UpdateChangelogEntry(ctx context.Context, arg UpdateChangelogEntryParams) (ChangelogEntry, error) {
	row := q.db.QueryRow(ctx, updateChangelogEntry,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Published,
		arg.PublishedAt,
	)
	var i ChangelogEntry
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.Body,
		&i.Published,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
