// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: component_groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createComponentGroup = `-- name: CreateComponentGroup :one
INSERT INTO component_groups (status_page_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, status_page_id, name, position, created_at, updated_at, deleted_at
`

type CreateComponentGroupParams struct {
	StatusPageID uuid.UUID
	Name         string
	Position     int32
}

func (q *Queries) CreateComponentGroup(ctx context.Context, arg CreateComponentGroupParams) (ComponentGroup, error) {
	row := q.db.QueryRow(ctx, createComponentGroup, arg.StatusPageID, arg.Name, arg.Position)
	var i ComponentGroup
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getComponentGroupByID = `-- name: GetComponentGroupByID :one
SELECT id, status_page_id, name, position, created_at, updated_at, deleted_at FROM component_groups WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetComponentGroupByID(ctx context.Context, id uuid.UUID) (ComponentGroup, error) {
	row := q.db.QueryRow(ctx, getComponentGroupByID, id)
	var i ComponentGroup
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listComponentGroupsByPage = `-- name: ListComponentGroupsByPage :many
SELECT id, status_page_id, name, position, created_at, updated_at, deleted_at FROM component_groups
WHERE status_page_id = $1 AND deleted_at IS NULL
ORDER BY position, name
`

func (q *Queries) ListComponentGroupsByPage(ctx context.Context, statusPageID uuid.UUID) ([]ComponentGroup, error) {
	rows, err := q.db.Query(ctx, listComponentGroupsByPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentGroup{}
	for rows.Next() {
		var i ComponentGroup
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComponentGroup = `-- name: SoftDeleteComponentGroup :exec
UPDATE component_groups SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComponentGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteComponentGroup, id)
	return err
}

const updateComponentGroup = `-- name: UpdateComponentGroup :one
UPDATE component_groups SET name = $2, position = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status_page_id, name, position, created_at, updated_at, deleted_at
`

type UpdateComponentGroupParams struct {
	ID       uuid.UUID
	Name     string
	Position int32
}

func (q *Queries) UpdateComponentGroup(ctx context.Context, arg UpdateComponentGroupParams) (ComponentGroup, error) {
	row := q.db.QueryRow(ctx, updateComponentGroup, arg.ID, arg.Name, arg.Position)
	var i ComponentGroup
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
