// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: components.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (
    status_page_id, group_id, parent_id, name, description, position,
    current_status, is_private, show_uptime, display_state
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, status_page_id, group_id, parent_id, name, description, position, current_status, is_private, show_uptime, display_state, created_at, updated_at, deleted_at
`

type CreateComponentParams struct {
	StatusPageID  uuid.UUID
	GroupID       *uuid.UUID
	ParentID      *uuid.UUID
	Name          string
	Description   string
	Position      int32
	CurrentStatus ComponentStatus
	IsPrivate     bool
	ShowUptime    bool
	DisplayState  bool
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.StatusPageID,
		arg.GroupID,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.Position,
		arg.CurrentStatus,
		arg.IsPrivate,
		arg.ShowUptime,
		arg.DisplayState,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.GroupID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CurrentStatus,
		&i.IsPrivate,
		&i.ShowUptime,
		&i.DisplayState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT id, status_page_id, group_id, parent_id, name, description, position, current_status, is_private, show_uptime, display_state, created_at, updated_at, deleted_at FROM components WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetComponentByID(ctx context.Context, id uuid.UUID) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByID, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.GroupID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CurrentStatus,
		&i.IsPrivate,
		&i.ShowUptime,
		&i.DisplayState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listComponentsByPage = `-- name: ListComponentsByPage :many
SELECT id, status_page_id, group_id, parent_id, name, description, position, current_status, is_private, show_uptime, display_state, created_at, updated_at, deleted_at FROM components
WHERE status_page_id = $1 AND deleted_at IS NULL
ORDER BY position, name
`

func (q *Queries) ListComponentsByPage(ctx context.Context, statusPageID uuid.UUID) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponentsByPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.GroupID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.CurrentStatus,
			&i.IsPrivate,
			&i.ShowUptime,
			&i.DisplayState,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setComponentStatus = `-- name: SetComponentStatus :one
UPDATE components SET current_status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status_page_id, group_id, parent_id, name, description, position, current_status, is_private, show_uptime, display_state, created_at, updated_at, deleted_at
`

type SetComponentStatusParams struct {
	ID            uuid.UUID
	CurrentStatus ComponentStatus
}

func (q *Queries) SetComponentStatus(ctx context.Context, arg SetComponentStatusParams) (Component, error) {
	row := q.db.QueryRow(ctx, setComponentStatus, arg.ID, arg.CurrentStatus)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.GroupID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CurrentStatus,
		&i.IsPrivate,
		&i.ShowUptime,
		&i.DisplayState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteComponent = `-- name: SoftDeleteComponent :exec
UPDATE components SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComponent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteComponent, id)
	return err
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components SET
    group_id = $2,
    parent_id = $3,
    name = $4,
    description = $5,
    position = $6,
    is_private = $7,
    show_uptime = $8,
    display_state = $9
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status_page_id, group_id, parent_id, name, description, position, current_status, is_private, show_uptime, display_state, created_at, updated_at, deleted_at
`

type UpdateComponentParams struct {
	ID           uuid.UUID
	GroupID      *uuid.UUID
	ParentID     *uuid.UUID
	Name         string
	Description  string
	Position     int32
	IsPrivate    bool
	ShowUptime   bool
	DisplayState bool
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.ID,
		arg.GroupID,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.Position,
		arg.IsPrivate,
		arg.ShowUptime,
		arg.DisplayState,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.GroupID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CurrentStatus,
		&i.IsPrivate,
		&i.ShowUptime,
		&i.DisplayState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
