// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_certificates.sql

package db

import (
	"context"
	"time"
)

const deleteACMEChallenge = `-- name: DeleteACMEChallenge :exec
DELETE FROM acme_challenges WHERE token = $1
`

func (q *Queries) DeleteACMEChallenge(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteACMEChallenge, token)
	return err
}

const deleteDomainCertificate = `-- name: DeleteDomainCertificate :exec
DELETE FROM domain_certificates WHERE domain = $1
`

func (q *Queries) DeleteDomainCertificate(ctx context.Context, domain string) error {
	_, err := q.db.Exec(ctx, deleteDomainCertificate, domain)
	return err
}

const getACMEAccount = `-- name: GetACMEAccount :one
SELECT directory_url, email, private_key, registration, created_at FROM acme_accounts WHERE directory_url = $1
`

func (q *Queries) GetACMEAccount(ctx context.Context, directoryUrl string) (AcmeAccount, error) {
	row := q.db.QueryRow(ctx, getACMEAccount, directoryUrl)
	var i AcmeAccount
	err := row.Scan(
		&i.DirectoryUrl,
		&i.Email,
		&i.PrivateKey,
		&i.Registration,
		&i.CreatedAt,
	)
	return i, err
}

const getACMEChallenge = `-- name: GetACMEChallenge :one
SELECT key_auth FROM acme_challenges WHERE token = $1
`

func (q *Queries) GetACMEChallenge(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, getACMEChallenge, token)
	var key_auth string
	err := row.Scan(&key_auth)
	return key_auth, err
}

const getDomainCertificate = `-- name: GetDomainCertificate :one
SELECT domain, cert_pem, key_pem, issued_at, expires_at, updated_at FROM domain_certificates WHERE domain = $1
`

func (q *Queries) GetDomainCertificate(ctx context.Context, domain string) (DomainCertificate, error) {
	row := q.db.QueryRow(ctx, getDomainCertificate, domain)
	var i DomainCertificate
	err := row.Scan(
		&i.Domain,
		&i.CertPem,
		&i.KeyPem,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlugByCustomDomain = `-- name: GetSlugByCustomDomain :one
SELECT slug FROM status_pages
WHERE custom_domain = $1 AND domain_verified = true AND deleted_at IS NULL
`

func (q *Queries) GetSlugByCustomDomain(ctx context.Context, customDomain *string) (string, error) {
	row := q.db.QueryRow(ctx, getSlugByCustomDomain, customDomain)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const listVerifiedDomains = `-- name: ListVerifiedDomains :many
SELECT custom_domain FROM status_pages
WHERE custom_domain IS NOT NULL AND domain_verified = true AND deleted_at IS NULL
`

func (q *Queries) ListVerifiedDomains(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, listVerifiedDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var custom_domain *string
		if err := rows.Scan(&custom_domain); err != nil {
			return nil, err
		}
		items = append(items, custom_domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putACMEChallenge = `-- name: PutACMEChallenge :exec
INSERT INTO acme_challenges (token, key_auth, domain)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET key_auth = EXCLUDED.key_auth, domain = EXCLUDED.domain
`

type PutACMEChallengeParams struct {
	Token   string
	KeyAuth string
	Domain  string
}

func (q *Queries) PutACMEChallenge(ctx context.Context, arg PutACMEChallengeParams) error {
	_, err := q.db.Exec(ctx, putACMEChallenge, arg.Token, arg.KeyAuth, arg.Domain)
	return err
}

const upsertACMEAccount = `-- name: UpsertACMEAccount :exec
INSERT INTO acme_accounts (directory_url, email, private_key, registration)
VALUES ($1, $2, $3, $4)
ON CONFLICT (directory_url) DO UPDATE
SET email = EXCLUDED.email, private_key = EXCLUDED.private_key, registration = EXCLUDED.registration
`

type UpsertACMEAccountParams struct {
	DirectoryUrl string
	Email        string
	PrivateKey   string
	Registration []byte
}

func (q *Queries) UpsertACMEAccount(ctx context.Context, arg UpsertACMEAccountParams) error {
	_, err := q.db.Exec(ctx, upsertACMEAccount,
		arg.DirectoryUrl,
		arg.Email,
		arg.PrivateKey,
		arg.Registration,
	)
	return err
}

const upsertDomainCertificate = `-- name: UpsertDomainCertificate :exec
INSERT INTO domain_certificates (domain, cert_pem, key_pem, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (domain) DO UPDATE
SET cert_pem = EXCLUDED.cert_pem, key_pem = EXCLUDED.key_pem, expires_at = EXCLUDED.expires_at
`

type UpsertDomainCertificateParams struct {
	Domain    string
	CertPem   string
	KeyPem    string
	ExpiresAt time.Time
}

func (q *Queries) UpsertDomainCertificate(ctx context.Context, arg UpsertDomainCertificateParams) error {
	_, err := q.db.Exec(ctx, upsertDomainCertificate,
		arg.Domain,
		arg.CertPem,
		arg.KeyPem,
		arg.ExpiresAt,
	)
	return err
}
