// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (status_page_id, account_id, source, region, subdomain, mode, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id, status_page_id, account_id, source, region, subdomain, mode, status, report, error, created_at, finished_at, updated_at
`

type CreateImportJobParams struct {
	StatusPageID uuid.UUID
	AccountID    uuid.UUID
	Source       string
	Region       *string
	Subdomain    string
	Mode         string
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.StatusPageID,
		arg.AccountID,
		arg.Source,
		arg.Region,
		arg.Subdomain,
		arg.Mode,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.AccountID,
		&i.Source,
		&i.Region,
		&i.Subdomain,
		&i.Mode,
		&i.Status,
		&i.Report,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalMapping = `-- name: GetExternalMapping :one
SELECT internal_id FROM external_id_map
WHERE status_page_id = $1 AND source = $2 AND entity_type = $3 AND external_id = $4
`

type GetExternalMappingParams struct {
	StatusPageID uuid.UUID
	Source       string
	EntityType   string
	ExternalID   string
}

func (q *Queries) GetExternalMapping(ctx context.Context, arg GetExternalMappingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getExternalMapping,
		arg.StatusPageID,
		arg.Source,
		arg.EntityType,
		arg.ExternalID,
	)
	var internal_id uuid.UUID
	err := row.Scan(&internal_id)
	return internal_id, err
}

const getImportJob = `-- name: GetImportJob :one
SELECT id, status_page_id, account_id, source, region, subdomain, mode, status, report, error, created_at, finished_at, updated_at FROM import_jobs WHERE id = $1
`

func (q *Queries) GetImportJob(ctx context.Context, id uuid.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJob, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.AccountID,
		&i.Source,
		&i.Region,
		&i.Subdomain,
		&i.Mode,
		&i.Status,
		&i.Report,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportJob = `-- name: UpdateImportJob :one
UPDATE import_jobs
SET status = $2, report = $3, error = $4, finished_at = $5
WHERE id = $1
RETURNING id, status_page_id, account_id, source, region, subdomain, mode, status, report, error, created_at, finished_at, updated_at
`

type UpdateImportJobParams struct {
	ID         uuid.UUID
	Status     string
	Report     []byte
	Error      *string
	FinishedAt *time.Time
}

func (q *Queries) UpdateImportJob(ctx context.Context, arg UpdateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJob,
		arg.ID,
		arg.Status,
		arg.Report,
		arg.Error,
		arg.FinishedAt,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.AccountID,
		&i.Source,
		&i.Region,
		&i.Subdomain,
		&i.Mode,
		&i.Status,
		&i.Report,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExternalMapping = `-- name: UpsertExternalMapping :exec
INSERT INTO external_id_map (status_page_id, source, entity_type, external_id, internal_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (status_page_id, source, entity_type, external_id)
DO UPDATE SET internal_id = EXCLUDED.internal_id
`

type UpsertExternalMappingParams struct {
	StatusPageID uuid.UUID
	Source       string
	EntityType   string
	ExternalID   string
	InternalID   uuid.UUID
}

func (q *Queries) UpsertExternalMapping(ctx context.Context, arg UpsertExternalMappingParams) error {
	_, err := q.db.Exec(ctx, upsertExternalMapping,
		arg.StatusPageID,
		arg.Source,
		arg.EntityType,
		arg.ExternalID,
		arg.InternalID,
	)
	return err
}
