// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incident_templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addIncidentTemplateComponent = `-- name: AddIncidentTemplateComponent :one

INSERT INTO incident_template_components (template_id, component_id, component_status_in_incident)
VALUES ($1, $2, $3)
RETURNING id, template_id, component_id, component_status_in_incident, created_at, updated_at
`

type AddIncidentTemplateComponentParams struct {
	TemplateID                uuid.UUID
	ComponentID               uuid.UUID
	ComponentStatusInIncident ComponentStatus
}

// ── incident_template_components ──
func (q *Queries) AddIncidentTemplateComponent(ctx context.Context, arg AddIncidentTemplateComponentParams) (IncidentTemplateComponent, error) {
	row := q.db.QueryRow(ctx, addIncidentTemplateComponent, arg.TemplateID, arg.ComponentID, arg.ComponentStatusInIncident)
	var i IncidentTemplateComponent
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ComponentID,
		&i.ComponentStatusInIncident,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncidentTemplate = `-- name: CreateIncidentTemplate :one

INSERT INTO incident_templates (
    status_page_id, name, title_tmpl, body_tmpl, default_impact
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status_page_id, name, title_tmpl, body_tmpl, default_impact, created_at, updated_at
`

type CreateIncidentTemplateParams struct {
	StatusPageID  uuid.UUID
	Name          string
	TitleTmpl     string
	BodyTmpl      string
	DefaultImpact IncidentImpact
}

// ── incident_templates ──
func (q *Queries) CreateIncidentTemplate(ctx context.Context, arg CreateIncidentTemplateParams) (IncidentTemplate, error) {
	row := q.db.QueryRow(ctx, createIncidentTemplate,
		arg.StatusPageID,
		arg.Name,
		arg.TitleTmpl,
		arg.BodyTmpl,
		arg.DefaultImpact,
	)
	var i IncidentTemplate
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Name,
		&i.TitleTmpl,
		&i.BodyTmpl,
		&i.DefaultImpact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncidentTemplate = `-- name: DeleteIncidentTemplate :exec
DELETE FROM incident_templates WHERE id = $1
`

func (q *Queries) DeleteIncidentTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncidentTemplate, id)
	return err
}

const deleteIncidentTemplateComponents = `-- name: DeleteIncidentTemplateComponents :exec
DELETE FROM incident_template_components WHERE template_id = $1
`

func (q *Queries) DeleteIncidentTemplateComponents(ctx context.Context, templateID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncidentTemplateComponents, templateID)
	return err
}

const getIncidentTemplateByID = `-- name: GetIncidentTemplateByID :one
SELECT id, status_page_id, name, title_tmpl, body_tmpl, default_impact, created_at, updated_at FROM incident_templates WHERE id = $1
`

func (q *Queries) GetIncidentTemplateByID(ctx context.Context, id uuid.UUID) (IncidentTemplate, error) {
	row := q.db.QueryRow(ctx, getIncidentTemplateByID, id)
	var i IncidentTemplate
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Name,
		&i.TitleTmpl,
		&i.BodyTmpl,
		&i.DefaultImpact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidentTemplateComponents = `-- name: ListIncidentTemplateComponents :many
SELECT id, template_id, component_id, component_status_in_incident, created_at, updated_at FROM incident_template_components WHERE template_id = $1 ORDER BY created_at
`

func (q *Queries) ListIncidentTemplateComponents(ctx context.Context, templateID uuid.UUID) ([]IncidentTemplateComponent, error) {
	rows, err := q.db.Query(ctx, listIncidentTemplateComponents, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentTemplateComponent{}
	for rows.Next() {
		var i IncidentTemplateComponent
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ComponentID,
			&i.ComponentStatusInIncident,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentTemplatesByPage = `-- name: ListIncidentTemplatesByPage :many
SELECT id, status_page_id, name, title_tmpl, body_tmpl, default_impact, created_at, updated_at FROM incident_templates WHERE status_page_id = $1 ORDER BY name
`

func (q *Queries) ListIncidentTemplatesByPage(ctx context.Context, statusPageID uuid.UUID) ([]IncidentTemplate, error) {
	rows, err := q.db.Query(ctx, listIncidentTemplatesByPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentTemplate{}
	for rows.Next() {
		var i IncidentTemplate
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Name,
			&i.TitleTmpl,
			&i.BodyTmpl,
			&i.DefaultImpact,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentTemplate = `-- name: UpdateIncidentTemplate :one
UPDATE incident_templates SET
    name = $2,
    title_tmpl = $3,
    body_tmpl = $4,
    default_impact = $5
WHERE id = $1
RETURNING id, status_page_id, name, title_tmpl, body_tmpl, default_impact, created_at, updated_at
`

type UpdateIncidentTemplateParams struct {
	ID            uuid.UUID
	Name          string
	TitleTmpl     string
	BodyTmpl      string
	DefaultImpact IncidentImpact
}

func (q *Queries) UpdateIncidentTemplate(ctx context.Context, arg UpdateIncidentTemplateParams) (IncidentTemplate, error) {
	row := q.db.QueryRow(ctx, updateIncidentTemplate,
		arg.ID,
		arg.Name,
		arg.TitleTmpl,
		arg.BodyTmpl,
		arg.DefaultImpact,
	)
	var i IncidentTemplate
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Name,
		&i.TitleTmpl,
		&i.BodyTmpl,
		&i.DefaultImpact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
