// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addIncidentComponent = `-- name: AddIncidentComponent :one

INSERT INTO incident_components (incident_id, component_id, component_status_in_incident)
VALUES ($1, $2, $3)
RETURNING id, incident_id, component_id, component_status_in_incident, created_at, updated_at
`

type AddIncidentComponentParams struct {
	IncidentID                uuid.UUID
	ComponentID               uuid.UUID
	ComponentStatusInIncident ComponentStatus
}

// ── incident_components ──
func (q *Queries) AddIncidentComponent(ctx context.Context, arg AddIncidentComponentParams) (IncidentComponent, error) {
	row := q.db.QueryRow(ctx, addIncidentComponent, arg.IncidentID, arg.ComponentID, arg.ComponentStatusInIncident)
	var i IncidentComponent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.ComponentID,
		&i.ComponentStatusInIncident,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addIncidentUpdate = `-- name: AddIncidentUpdate :one

INSERT INTO incident_updates (incident_id, status, body, notify_subscribers)
VALUES ($1, $2, $3, $4)
RETURNING id, incident_id, status, body, notify_subscribers, created_at, updated_at
`

type AddIncidentUpdateParams struct {
	IncidentID        uuid.UUID
	Status            IncidentStatus
	Body              string
	NotifySubscribers bool
}

// ── incident_updates ──
func (q *Queries) AddIncidentUpdate(ctx context.Context, arg AddIncidentUpdateParams) (IncidentUpdate, error) {
	row := q.db.QueryRow(ctx, addIncidentUpdate,
		arg.IncidentID,
		arg.Status,
		arg.Body,
		arg.NotifySubscribers,
	)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Body,
		&i.NotifySubscribers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countIncidents = `-- name: CountIncidents :one
SELECT count(*) FROM incidents
WHERE status_page_id = $1
  AND deleted_at IS NULL
  AND ($2::incident_status IS NULL OR current_status = $2)
  AND ($3::incident_impact IS NULL OR impact = $3)
  AND ($4::uuid IS NULL OR id IN (
        SELECT incident_id FROM incident_components WHERE component_id = $4))
`

type CountIncidentsParams struct {
	StatusPageID uuid.UUID
	Status       NullIncidentStatus
	Impact       NullIncidentImpact
	ComponentID  *uuid.UUID
}

func (q *Queries) CountIncidents(ctx context.Context, arg CountIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidents,
		arg.StatusPageID,
		arg.Status,
		arg.Impact,
		arg.ComponentID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicIncidents = `-- name: CountPublicIncidents :one
SELECT count(*) FROM incidents
WHERE status_page_id = $1
  AND deleted_at IS NULL
  AND is_visible = true
  AND ($2::incident_status IS NULL OR current_status = $2)
  AND ($3::incident_impact IS NULL OR impact = $3)
  AND ($4::uuid IS NULL OR id IN (
        SELECT incident_id FROM incident_components WHERE component_id = $4))
`

type CountPublicIncidentsParams struct {
	StatusPageID uuid.UUID
	Status       NullIncidentStatus
	Impact       NullIncidentImpact
	ComponentID  *uuid.UUID
}

func (q *Queries) CountPublicIncidents(ctx context.Context, arg CountPublicIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicIncidents,
		arg.StatusPageID,
		arg.Status,
		arg.Impact,
		arg.ComponentID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncident = `-- name: CreateIncident :one

INSERT INTO incidents (
    status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible,
    integration_id, external_dedup_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at, integration_id, external_dedup_key
`

type CreateIncidentParams struct {
	StatusPageID     uuid.UUID
	Title            string
	CurrentStatus    IncidentStatus
	Impact           IncidentImpact
	StartedAt        time.Time
	ResolvedAt       *time.Time
	Postmortem       *string
	IsVisible        bool
	IntegrationID    *uuid.UUID
	ExternalDedupKey *string
}

// ── incidents ──
func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.StatusPageID,
		arg.Title,
		arg.CurrentStatus,
		arg.Impact,
		arg.StartedAt,
		arg.ResolvedAt,
		arg.Postmortem,
		arg.IsVisible,
		arg.IntegrationID,
		arg.ExternalDedupKey,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.CurrentStatus,
		&i.Impact,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Postmortem,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IntegrationID,
		&i.ExternalDedupKey,
	)
	return i, err
}

const deleteIncidentComponents = `-- name: DeleteIncidentComponents :exec
DELETE FROM incident_components WHERE incident_id = $1
`

func (q *Queries) DeleteIncidentComponents(ctx context.Context, incidentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncidentComponents, incidentID)
	return err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at, integration_id, external_dedup_key FROM incidents WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetIncidentByID(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.CurrentStatus,
		&i.Impact,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Postmortem,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IntegrationID,
		&i.ExternalDedupKey,
	)
	return i, err
}

const getOpenIncidentByDedup = `-- name: GetOpenIncidentByDedup :one
SELECT id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at, integration_id, external_dedup_key FROM incidents
WHERE status_page_id = $1 AND external_dedup_key = $2
  AND resolved_at IS NULL AND deleted_at IS NULL
`

type GetOpenIncidentByDedupParams struct {
	StatusPageID     uuid.UUID
	ExternalDedupKey *string
}

func (q *Queries) GetOpenIncidentByDedup(ctx context.Context, arg GetOpenIncidentByDedupParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getOpenIncidentByDedup, arg.StatusPageID, arg.ExternalDedupKey)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.CurrentStatus,
		&i.Impact,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Postmortem,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IntegrationID,
		&i.ExternalDedupKey,
	)
	return i, err
}

const listActiveIncidentComponentStatuses = `-- name: ListActiveIncidentComponentStatuses :many
SELECT ic.component_id, ic.component_status_in_incident
FROM incident_components ic
JOIN incidents i ON i.id = ic.incident_id
WHERE i.status_page_id = $1
  AND i.deleted_at IS NULL
  AND i.current_status <> 'resolved'
`

type ListActiveIncidentComponentStatusesRow struct {
	ComponentID               uuid.UUID
	ComponentStatusInIncident ComponentStatus
}

// Плоский список (component_id, статус) по всем активным (не resolved, не удалённым) инцидентам
// страницы — основа авто-деривации статуса компонентов (DESIGN §3.3, §6).
func (q *Queries) ListActiveIncidentComponentStatuses(ctx context.Context, statusPageID uuid.UUID) ([]ListActiveIncidentComponentStatusesRow, error) {
	rows, err := q.db.Query(ctx, listActiveIncidentComponentStatuses, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveIncidentComponentStatusesRow{}
	for rows.Next() {
		var i ListActiveIncidentComponentStatusesRow
		if err := rows.Scan(&i.ComponentID, &i.ComponentStatusInIncident); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePublicIncidents = `-- name: ListActivePublicIncidents :many
SELECT id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at, integration_id, external_dedup_key FROM incidents
WHERE status_page_id = $1
  AND deleted_at IS NULL
  AND is_visible = true
  AND current_status <> 'resolved'
ORDER BY started_at DESC
`

// Активные (не resolved, видимые) инциденты страницы — для публичной сводки.
func (q *Queries) ListActivePublicIncidents(ctx context.Context, statusPageID uuid.UUID) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listActivePublicIncidents, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Title,
			&i.CurrentStatus,
			&i.Impact,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.Postmortem,
			&i.IsVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IntegrationID,
			&i.ExternalDedupKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentComponents = `-- name: ListIncidentComponents :many
SELECT id, incident_id, component_id, component_status_in_incident, created_at, updated_at FROM incident_components WHERE incident_id = $1 ORDER BY created_at
`

func (q *Queries) ListIncidentComponents(ctx context.Context, incidentID uuid.UUID) ([]IncidentComponent, error) {
	rows, err := q.db.Query(ctx, listIncidentComponents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentComponent{}
	for rows.Next() {
		var i IncidentComponent
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.ComponentID,
			&i.ComponentStatusInIncident,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentUpdates = `-- name: ListIncidentUpdates :many
SELECT id, incident_id, status, body, notify_subscribers, created_at, updated_at FROM incident_updates WHERE incident_id = $1 ORDER BY created_at
`

func (q *Queries) ListIncidentUpdates(ctx context.Context, incidentID uuid.UUID) ([]IncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listIncidentUpdates, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentUpdate{}
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Body,
			&i.NotifySubscribers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at, integration_id, external_dedup_key FROM incidents
WHERE status_page_id = $1
  AND deleted_at IS NULL
  AND ($2::incident_status IS NULL OR current_status = $2)
  AND ($3::incident_impact IS NULL OR impact = $3)
  AND ($4::uuid IS NULL OR id IN (
        SELECT incident_id FROM incident_components WHERE component_id = $4))
ORDER BY started_at DESC
LIMIT $6 OFFSET $5
`

type ListIncidentsParams struct {
	StatusPageID uuid.UUID
	Status       NullIncidentStatus
	Impact       NullIncidentImpact
	ComponentID  *uuid.UUID
	Off          int32
	Lim          int32
}

// Админский список инцидентов страницы: не удалённые, но **включая скрытые** (is_visible любое),
// с теми же фильтрами и пагинацией, что и публичная история. Для управления оператором.
func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents,
		arg.StatusPageID,
		arg.Status,
		arg.Impact,
		arg.ComponentID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Title,
			&i.CurrentStatus,
			&i.Impact,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.Postmortem,
			&i.IsVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IntegrationID,
			&i.ExternalDedupKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicIncidents = `-- name: ListPublicIncidents :many
SELECT id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at, integration_id, external_dedup_key FROM incidents
WHERE status_page_id = $1
  AND deleted_at IS NULL
  AND is_visible = true
  AND ($2::incident_status IS NULL OR current_status = $2)
  AND ($3::incident_impact IS NULL OR impact = $3)
  AND ($4::uuid IS NULL OR id IN (
        SELECT incident_id FROM incident_components WHERE component_id = $4))
ORDER BY started_at DESC
LIMIT $6 OFFSET $5
`

type ListPublicIncidentsParams struct {
	StatusPageID uuid.UUID
	Status       NullIncidentStatus
	Impact       NullIncidentImpact
	ComponentID  *uuid.UUID
	Off          int32
	Lim          int32
}

// Публичная история инцидентов страницы: только видимые и не удалённые, с опциональными
// фильтрами (статус, impact, затронутый компонент) и пагинацией (DESIGN §3.3).
func (q *Queries) ListPublicIncidents(ctx context.Context, arg ListPublicIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listPublicIncidents,
		arg.StatusPageID,
		arg.Status,
		arg.Impact,
		arg.ComponentID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Title,
			&i.CurrentStatus,
			&i.Impact,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.Postmortem,
			&i.IsVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IntegrationID,
			&i.ExternalDedupKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteIncident = `-- name: SoftDeleteIncident :exec
UPDATE incidents SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteIncident(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteIncident, id)
	return err
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents SET
    title = $2,
    current_status = $3,
    impact = $4,
    resolved_at = $5,
    postmortem = $6,
    is_visible = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at, integration_id, external_dedup_key
`

type UpdateIncidentParams struct {
	ID            uuid.UUID
	Title         string
	CurrentStatus IncidentStatus
	Impact        IncidentImpact
	ResolvedAt    *time.Time
	Postmortem    *string
	IsVisible     bool
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.ID,
		arg.Title,
		arg.CurrentStatus,
		arg.Impact,
		arg.ResolvedAt,
		arg.Postmortem,
		arg.IsVisible,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.CurrentStatus,
		&i.Impact,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Postmortem,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IntegrationID,
		&i.ExternalDedupKey,
	)
	return i, err
}
