// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addIncidentComponent = `-- name: AddIncidentComponent :one

INSERT INTO incident_components (incident_id, component_id, component_status_in_incident)
VALUES ($1, $2, $3)
RETURNING id, incident_id, component_id, component_status_in_incident, created_at, updated_at
`

type AddIncidentComponentParams struct {
	IncidentID                uuid.UUID
	ComponentID               uuid.UUID
	ComponentStatusInIncident ComponentStatus
}

// ── incident_components ──
func (q *Queries) AddIncidentComponent(ctx context.Context, arg AddIncidentComponentParams) (IncidentComponent, error) {
	row := q.db.QueryRow(ctx, addIncidentComponent, arg.IncidentID, arg.ComponentID, arg.ComponentStatusInIncident)
	var i IncidentComponent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.ComponentID,
		&i.ComponentStatusInIncident,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addIncidentUpdate = `-- name: AddIncidentUpdate :one

INSERT INTO incident_updates (incident_id, status, body, notify_subscribers)
VALUES ($1, $2, $3, $4)
RETURNING id, incident_id, status, body, notify_subscribers, created_at, updated_at
`

type AddIncidentUpdateParams struct {
	IncidentID        uuid.UUID
	Status            IncidentStatus
	Body              string
	NotifySubscribers bool
}

// ── incident_updates ──
func (q *Queries) AddIncidentUpdate(ctx context.Context, arg AddIncidentUpdateParams) (IncidentUpdate, error) {
	row := q.db.QueryRow(ctx, addIncidentUpdate,
		arg.IncidentID,
		arg.Status,
		arg.Body,
		arg.NotifySubscribers,
	)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Body,
		&i.NotifySubscribers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncident = `-- name: CreateIncident :one

INSERT INTO incidents (
    status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at
`

type CreateIncidentParams struct {
	StatusPageID  uuid.UUID
	Title         string
	CurrentStatus IncidentStatus
	Impact        IncidentImpact
	StartedAt     time.Time
	ResolvedAt    *time.Time
	Postmortem    *string
	IsVisible     bool
}

// ── incidents ──
func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.StatusPageID,
		arg.Title,
		arg.CurrentStatus,
		arg.Impact,
		arg.StartedAt,
		arg.ResolvedAt,
		arg.Postmortem,
		arg.IsVisible,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.CurrentStatus,
		&i.Impact,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Postmortem,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteIncidentComponents = `-- name: DeleteIncidentComponents :exec
DELETE FROM incident_components WHERE incident_id = $1
`

func (q *Queries) DeleteIncidentComponents(ctx context.Context, incidentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncidentComponents, incidentID)
	return err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at FROM incidents WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetIncidentByID(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.CurrentStatus,
		&i.Impact,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Postmortem,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveIncidentComponentStatuses = `-- name: ListActiveIncidentComponentStatuses :many
SELECT ic.component_id, ic.component_status_in_incident
FROM incident_components ic
JOIN incidents i ON i.id = ic.incident_id
WHERE i.status_page_id = $1
  AND i.deleted_at IS NULL
  AND i.current_status <> 'resolved'
`

type ListActiveIncidentComponentStatusesRow struct {
	ComponentID               uuid.UUID
	ComponentStatusInIncident ComponentStatus
}

// Плоский список (component_id, статус) по всем активным (не resolved, не удалённым) инцидентам
// страницы — основа авто-деривации статуса компонентов (DESIGN §3.3, §6).
func (q *Queries) ListActiveIncidentComponentStatuses(ctx context.Context, statusPageID uuid.UUID) ([]ListActiveIncidentComponentStatusesRow, error) {
	rows, err := q.db.Query(ctx, listActiveIncidentComponentStatuses, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveIncidentComponentStatusesRow{}
	for rows.Next() {
		var i ListActiveIncidentComponentStatusesRow
		if err := rows.Scan(&i.ComponentID, &i.ComponentStatusInIncident); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentComponents = `-- name: ListIncidentComponents :many
SELECT id, incident_id, component_id, component_status_in_incident, created_at, updated_at FROM incident_components WHERE incident_id = $1 ORDER BY created_at
`

func (q *Queries) ListIncidentComponents(ctx context.Context, incidentID uuid.UUID) ([]IncidentComponent, error) {
	rows, err := q.db.Query(ctx, listIncidentComponents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentComponent{}
	for rows.Next() {
		var i IncidentComponent
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.ComponentID,
			&i.ComponentStatusInIncident,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentUpdates = `-- name: ListIncidentUpdates :many
SELECT id, incident_id, status, body, notify_subscribers, created_at, updated_at FROM incident_updates WHERE incident_id = $1 ORDER BY created_at
`

func (q *Queries) ListIncidentUpdates(ctx context.Context, incidentID uuid.UUID) ([]IncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listIncidentUpdates, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentUpdate{}
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Body,
			&i.NotifySubscribers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteIncident = `-- name: SoftDeleteIncident :exec
UPDATE incidents SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteIncident(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteIncident, id)
	return err
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents SET
    title = $2,
    current_status = $3,
    impact = $4,
    resolved_at = $5,
    postmortem = $6,
    is_visible = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status_page_id, title, current_status, impact, started_at, resolved_at, postmortem, is_visible, created_at, updated_at, deleted_at
`

type UpdateIncidentParams struct {
	ID            uuid.UUID
	Title         string
	CurrentStatus IncidentStatus
	Impact        IncidentImpact
	ResolvedAt    *time.Time
	Postmortem    *string
	IsVisible     bool
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.ID,
		arg.Title,
		arg.CurrentStatus,
		arg.Impact,
		arg.ResolvedAt,
		arg.Postmortem,
		arg.IsVisible,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.CurrentStatus,
		&i.Impact,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Postmortem,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
