// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenances.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMaintenanceComponent = `-- name: AddMaintenanceComponent :one

INSERT INTO maintenance_components (maintenance_id, component_id)
VALUES ($1, $2)
RETURNING id, maintenance_id, component_id, created_at, updated_at
`

type AddMaintenanceComponentParams struct {
	MaintenanceID uuid.UUID
	ComponentID   uuid.UUID
}

// ── maintenance_components ──
func (q *Queries) AddMaintenanceComponent(ctx context.Context, arg AddMaintenanceComponentParams) (MaintenanceComponent, error) {
	row := q.db.QueryRow(ctx, addMaintenanceComponent, arg.MaintenanceID, arg.ComponentID)
	var i MaintenanceComponent
	err := row.Scan(
		&i.ID,
		&i.MaintenanceID,
		&i.ComponentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addMaintenanceUpdate = `-- name: AddMaintenanceUpdate :one

INSERT INTO maintenance_updates (maintenance_id, body, notify_subscribers)
VALUES ($1, $2, $3)
RETURNING id, maintenance_id, body, notify_subscribers, created_at, updated_at
`

type AddMaintenanceUpdateParams struct {
	MaintenanceID     uuid.UUID
	Body              string
	NotifySubscribers bool
}

// ── maintenance_updates ──
func (q *Queries) AddMaintenanceUpdate(ctx context.Context, arg AddMaintenanceUpdateParams) (MaintenanceUpdate, error) {
	row := q.db.QueryRow(ctx, addMaintenanceUpdate, arg.MaintenanceID, arg.Body, arg.NotifySubscribers)
	var i MaintenanceUpdate
	err := row.Scan(
		&i.ID,
		&i.MaintenanceID,
		&i.Body,
		&i.NotifySubscribers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPublicMaintenances = `-- name: CountPublicMaintenances :one
SELECT count(*) FROM maintenances
WHERE status_page_id = $1
  AND deleted_at IS NULL
  AND ($2::maintenance_status IS NULL OR status = $2)
`

type CountPublicMaintenancesParams struct {
	StatusPageID uuid.UUID
	Status       NullMaintenanceStatus
}

func (q *Queries) CountPublicMaintenances(ctx context.Context, arg CountPublicMaintenancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicMaintenances, arg.StatusPageID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenance = `-- name: CreateMaintenance :one

INSERT INTO maintenances (
    status_page_id, title, description, status, scheduled_start, scheduled_end, started_at, completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, status_page_id, title, description, status, scheduled_start, scheduled_end, started_at, completed_at, created_at, updated_at, deleted_at
`

type CreateMaintenanceParams struct {
	StatusPageID   uuid.UUID
	Title          string
	Description    string
	Status         MaintenanceStatus
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	StartedAt      *time.Time
	CompletedAt    *time.Time
}

// ── maintenances ──
func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRow(ctx, createMaintenance,
		arg.StatusPageID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMaintenanceComponents = `-- name: DeleteMaintenanceComponents :exec
DELETE FROM maintenance_components WHERE maintenance_id = $1
`

func (q *Queries) DeleteMaintenanceComponents(ctx context.Context, maintenanceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceComponents, maintenanceID)
	return err
}

const getMaintenanceByID = `-- name: GetMaintenanceByID :one
SELECT id, status_page_id, title, description, status, scheduled_start, scheduled_end, started_at, completed_at, created_at, updated_at, deleted_at FROM maintenances WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMaintenanceByID(ctx context.Context, id uuid.UUID) (Maintenance, error) {
	row := q.db.QueryRow(ctx, getMaintenanceByID, id)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveMaintenanceComponentIDs = `-- name: ListActiveMaintenanceComponentIDs :many
SELECT mc.component_id
FROM maintenance_components mc
JOIN maintenances m ON m.id = mc.maintenance_id
WHERE m.status_page_id = $1
  AND m.deleted_at IS NULL
  AND m.status = 'in_progress'
`

// Список component_id всех активных (in_progress, не удалённых) работ страницы — основа
// авто-перевода компонентов в under_maintenance (DESIGN §3.4, §6).
func (q *Queries) ListActiveMaintenanceComponentIDs(ctx context.Context, statusPageID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveMaintenanceComponentIDs, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var component_id uuid.UUID
		if err := rows.Scan(&component_id); err != nil {
			return nil, err
		}
		items = append(items, component_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePublicMaintenances = `-- name: ListActivePublicMaintenances :many
SELECT id, status_page_id, title, description, status, scheduled_start, scheduled_end, started_at, completed_at, created_at, updated_at, deleted_at FROM maintenances
WHERE status_page_id = $1
  AND deleted_at IS NULL
  AND status <> 'completed'
ORDER BY scheduled_start
`

// Активные (не завершённые: scheduled + in_progress) работы страницы — для публичной сводки;
// ближайшие/идущие первыми.
func (q *Queries) ListActivePublicMaintenances(ctx context.Context, statusPageID uuid.UUID) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, listActivePublicMaintenances, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceComponents = `-- name: ListMaintenanceComponents :many
SELECT id, maintenance_id, component_id, created_at, updated_at FROM maintenance_components WHERE maintenance_id = $1 ORDER BY created_at
`

func (q *Queries) ListMaintenanceComponents(ctx context.Context, maintenanceID uuid.UUID) ([]MaintenanceComponent, error) {
	rows, err := q.db.Query(ctx, listMaintenanceComponents, maintenanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceComponent{}
	for rows.Next() {
		var i MaintenanceComponent
		if err := rows.Scan(
			&i.ID,
			&i.MaintenanceID,
			&i.ComponentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceUpdates = `-- name: ListMaintenanceUpdates :many
SELECT id, maintenance_id, body, notify_subscribers, created_at, updated_at FROM maintenance_updates WHERE maintenance_id = $1 ORDER BY created_at
`

func (q *Queries) ListMaintenanceUpdates(ctx context.Context, maintenanceID uuid.UUID) ([]MaintenanceUpdate, error) {
	rows, err := q.db.Query(ctx, listMaintenanceUpdates, maintenanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceUpdate{}
	for rows.Next() {
		var i MaintenanceUpdate
		if err := rows.Scan(
			&i.ID,
			&i.MaintenanceID,
			&i.Body,
			&i.NotifySubscribers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicMaintenances = `-- name: ListPublicMaintenances :many
SELECT id, status_page_id, title, description, status, scheduled_start, scheduled_end, started_at, completed_at, created_at, updated_at, deleted_at FROM maintenances
WHERE status_page_id = $1
  AND deleted_at IS NULL
  AND ($2::maintenance_status IS NULL OR status = $2)
ORDER BY scheduled_start DESC
LIMIT $4 OFFSET $3
`

type ListPublicMaintenancesParams struct {
	StatusPageID uuid.UUID
	Status       NullMaintenanceStatus
	Off          int32
	Lim          int32
}

// Публичный список работ страницы: не удалённые, с опциональным фильтром по статусу и пагинацией.
func (q *Queries) ListPublicMaintenances(ctx context.Context, arg ListPublicMaintenancesParams) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, listPublicMaintenances,
		arg.StatusPageID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maintenance{}
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ScheduledStart,
			&i.ScheduledEnd,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMaintenance = `-- name: SoftDeleteMaintenance :exec
UPDATE maintenances SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMaintenance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMaintenance, id)
	return err
}

const updateMaintenance = `-- name: UpdateMaintenance :one
UPDATE maintenances SET
    title = $2,
    description = $3,
    status = $4,
    scheduled_start = $5,
    scheduled_end = $6,
    started_at = $7,
    completed_at = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status_page_id, title, description, status, scheduled_start, scheduled_end, started_at, completed_at, created_at, updated_at, deleted_at
`

type UpdateMaintenanceParams struct {
	ID             uuid.UUID
	Title          string
	Description    string
	Status         MaintenanceStatus
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	StartedAt      *time.Time
	CompletedAt    *time.Time
}

func (q *Queries) UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRow(ctx, updateMaintenance,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
