// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: memberships.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (user_id, status_page_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, status_page_id, role, created_at, updated_at
`

type CreateMembershipParams struct {
	UserID       uuid.UUID
	StatusPageID uuid.UUID
	Role         string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.StatusPageID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StatusPageID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, status_page_id, role, created_at, updated_at FROM memberships WHERE user_id = $1 AND status_page_id = $2
`

type GetMembershipParams struct {
	UserID       uuid.UUID
	StatusPageID uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.StatusPageID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StatusPageID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT id, user_id, status_page_id, role, created_at, updated_at FROM memberships WHERE user_id = $1
`

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StatusPageID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
