// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BillingPlan string

const (
	BillingPlanFree    BillingPlan = "free"
	BillingPlanPremium BillingPlan = "premium"
)

func (e *BillingPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingPlan(s)
	case string:
		*e = BillingPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingPlan: %T", src)
	}
	return nil
}

type NullBillingPlan struct {
	BillingPlan BillingPlan
	Valid       bool // Valid is true if BillingPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingPlan) Scan(value interface{}) error {
	if value == nil {
		ns.BillingPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingPlan), nil
}

type ComponentStatus string

const (
	ComponentStatusOperational         ComponentStatus = "operational"
	ComponentStatusDegradedPerformance ComponentStatus = "degraded_performance"
	ComponentStatusPartialOutage       ComponentStatus = "partial_outage"
	ComponentStatusMajorOutage         ComponentStatus = "major_outage"
	ComponentStatusUnderMaintenance    ComponentStatus = "under_maintenance"
)

func (e *ComponentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComponentStatus(s)
	case string:
		*e = ComponentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ComponentStatus: %T", src)
	}
	return nil
}

type NullComponentStatus struct {
	ComponentStatus ComponentStatus
	Valid           bool // Valid is true if ComponentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComponentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ComponentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComponentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComponentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComponentStatus), nil
}

type IncidentImpact string

const (
	IncidentImpactNone     IncidentImpact = "none"
	IncidentImpactMinor    IncidentImpact = "minor"
	IncidentImpactMajor    IncidentImpact = "major"
	IncidentImpactCritical IncidentImpact = "critical"
)

func (e *IncidentImpact) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentImpact(s)
	case string:
		*e = IncidentImpact(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentImpact: %T", src)
	}
	return nil
}

type NullIncidentImpact struct {
	IncidentImpact IncidentImpact
	Valid          bool // Valid is true if IncidentImpact is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentImpact) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentImpact, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentImpact.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentImpact) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentImpact), nil
}

type IncidentStatus string

const (
	IncidentStatusInvestigating IncidentStatus = "investigating"
	IncidentStatusIdentified    IncidentStatus = "identified"
	IncidentStatusMonitoring    IncidentStatus = "monitoring"
	IncidentStatusResolved      IncidentStatus = "resolved"
)

func (e *IncidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentStatus(s)
	case string:
		*e = IncidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentStatus: %T", src)
	}
	return nil
}

type NullIncidentStatus struct {
	IncidentStatus IncidentStatus
	Valid          bool // Valid is true if IncidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentStatus), nil
}

type MaintenanceStatus string

const (
	MaintenanceStatusScheduled  MaintenanceStatus = "scheduled"
	MaintenanceStatusInProgress MaintenanceStatus = "in_progress"
	MaintenanceStatusCompleted  MaintenanceStatus = "completed"
)

func (e *MaintenanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenanceStatus(s)
	case string:
		*e = MaintenanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenanceStatus: %T", src)
	}
	return nil
}

type NullMaintenanceStatus struct {
	MaintenanceStatus MaintenanceStatus
	Valid             bool // Valid is true if MaintenanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenanceStatus), nil
}

type Account struct {
	ID          uuid.UUID
	Name        string
	BillingPlan BillingPlan
	OwnerUserID uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AcmeAccount struct {
	DirectoryUrl string
	Email        string
	PrivateKey   string
	Registration []byte
	CreatedAt    time.Time
}

type AcmeChallenge struct {
	Token     string
	KeyAuth   string
	Domain    string
	CreatedAt time.Time
}

type ApiToken struct {
	ID           uuid.UUID
	StatusPageID uuid.UUID
	TokenHash    string
	Name         string
	Scopes       []string
	LastUsedAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Component struct {
	ID            uuid.UUID
	StatusPageID  uuid.UUID
	GroupID       *uuid.UUID
	ParentID      *uuid.UUID
	Name          string
	Description   string
	Position      int32
	CurrentStatus ComponentStatus
	IsPrivate     bool
	ShowUptime    bool
	DisplayState  bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type ComponentGroup struct {
	ID           uuid.UUID
	StatusPageID uuid.UUID
	Name         string
	Position     int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type ComponentStatusHistory struct {
	ID          uuid.UUID
	ComponentID uuid.UUID
	Status      ComponentStatus
	StartedAt   time.Time
	EndedAt     *time.Time
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DomainCertificate struct {
	Domain    string
	CertPem   string
	KeyPem    string
	IssuedAt  time.Time
	ExpiresAt time.Time
	UpdatedAt time.Time
}

type Incident struct {
	ID            uuid.UUID
	StatusPageID  uuid.UUID
	Title         string
	CurrentStatus IncidentStatus
	Impact        IncidentImpact
	StartedAt     time.Time
	ResolvedAt    *time.Time
	Postmortem    *string
	IsVisible     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type IncidentComponent struct {
	ID                        uuid.UUID
	IncidentID                uuid.UUID
	ComponentID               uuid.UUID
	ComponentStatusInIncident ComponentStatus
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type IncidentTemplate struct {
	ID            uuid.UUID
	StatusPageID  uuid.UUID
	Name          string
	TitleTmpl     string
	BodyTmpl      string
	DefaultImpact IncidentImpact
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type IncidentTemplateComponent struct {
	ID                        uuid.UUID
	TemplateID                uuid.UUID
	ComponentID               uuid.UUID
	ComponentStatusInIncident ComponentStatus
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type IncidentUpdate struct {
	ID                uuid.UUID
	IncidentID        uuid.UUID
	Status            IncidentStatus
	Body              string
	NotifySubscribers bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Maintenance struct {
	ID             uuid.UUID
	StatusPageID   uuid.UUID
	Title          string
	Description    string
	Status         MaintenanceStatus
	ScheduledStart time.Time
	ScheduledEnd   time.Time
	StartedAt      *time.Time
	CompletedAt    *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type MaintenanceComponent struct {
	ID            uuid.UUID
	MaintenanceID uuid.UUID
	ComponentID   uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type MaintenanceUpdate struct {
	ID                uuid.UUID
	MaintenanceID     uuid.UUID
	Body              string
	NotifySubscribers bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Membership struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	StatusPageID uuid.UUID
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Notification struct {
	ID           uuid.UUID
	SubscriberID uuid.UUID
	EventType    string
	Payload      []byte
	Status       string
	Attempts     int32
	SentAt       *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PageAllowedEmail struct {
	ID           uuid.UUID
	StatusPageID uuid.UUID
	Email        string
	CreatedAt    time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type StatusPage struct {
	ID             uuid.UUID
	AccountID      uuid.UUID
	Name           string
	Description    string
	Slug           string
	Timezone       string
	DefaultLocale  string
	Visibility     string
	PasswordHash   *string
	CustomDomain   *string
	DomainVerified bool
	Theme          []byte
	LogoUrl        *string
	FaviconUrl     *string
	HidePoweredBy  bool
	SmtpConfig     []byte
	FromEmail      *string
	RedirectUrl    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type Subscriber struct {
	ID               uuid.UUID
	StatusPageID     uuid.UUID
	Channel          string
	Address          string
	Confirmed        bool
	ConfirmToken     *string
	UnsubscribeToken *string
	Scope            string
	ComponentIds     []uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Locale       string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
