// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingPlan string

const (
	BillingPlanFree    BillingPlan = "free"
	BillingPlanPremium BillingPlan = "premium"
)

func (e *BillingPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingPlan(s)
	case string:
		*e = BillingPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingPlan: %T", src)
	}
	return nil
}

type NullBillingPlan struct {
	BillingPlan BillingPlan
	Valid       bool // Valid is true if BillingPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingPlan) Scan(value interface{}) error {
	if value == nil {
		ns.BillingPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingPlan), nil
}

type ComponentStatus string

const (
	ComponentStatusOperational         ComponentStatus = "operational"
	ComponentStatusDegradedPerformance ComponentStatus = "degraded_performance"
	ComponentStatusPartialOutage       ComponentStatus = "partial_outage"
	ComponentStatusMajorOutage         ComponentStatus = "major_outage"
	ComponentStatusUnderMaintenance    ComponentStatus = "under_maintenance"
)

func (e *ComponentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComponentStatus(s)
	case string:
		*e = ComponentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ComponentStatus: %T", src)
	}
	return nil
}

type NullComponentStatus struct {
	ComponentStatus ComponentStatus
	Valid           bool // Valid is true if ComponentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComponentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ComponentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComponentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComponentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComponentStatus), nil
}

type Account struct {
	ID          uuid.UUID
	Name        string
	BillingPlan BillingPlan
	OwnerUserID uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Component struct {
	ID            uuid.UUID
	StatusPageID  uuid.UUID
	GroupID       *uuid.UUID
	ParentID      *uuid.UUID
	Name          string
	Description   string
	Position      int32
	CurrentStatus ComponentStatus
	IsPrivate     bool
	ShowUptime    bool
	DisplayState  bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type ComponentGroup struct {
	ID           uuid.UUID
	StatusPageID uuid.UUID
	Name         string
	Position     int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type ComponentStatusHistory struct {
	ID          uuid.UUID
	ComponentID uuid.UUID
	Status      ComponentStatus
	StartedAt   time.Time
	EndedAt     *time.Time
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Membership struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	StatusPageID uuid.UUID
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type StatusPage struct {
	ID             uuid.UUID
	AccountID      uuid.UUID
	Name           string
	Description    string
	Slug           string
	Timezone       string
	DefaultLocale  string
	Visibility     string
	PasswordHash   pgtype.Text
	CustomDomain   pgtype.Text
	DomainVerified bool
	Theme          []byte
	LogoUrl        pgtype.Text
	FaviconUrl     pgtype.Text
	HidePoweredBy  bool
	SmtpConfig     []byte
	FromEmail      pgtype.Text
	RedirectUrl    pgtype.Text
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Locale       string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
