// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (subscriber_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, subscriber_id, event_type, payload, status, attempts, sent_at, created_at, updated_at
`

type CreateNotificationParams struct {
	SubscriberID uuid.UUID
	EventType    string
	Payload      []byte
}

// ── notifications (журнал отправок / идемпотентность, DESIGN §8.1) ──
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.SubscriberID, arg.EventType, arg.Payload)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.SubscriberID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, subscriber_id, event_type, payload, status, attempts, sent_at, created_at, updated_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.SubscriberID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementNotificationAttempts = `-- name: IncrementNotificationAttempts :one
UPDATE notifications SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

// Увеличивает счётчик попыток и возвращает новое значение (для расчёта backoff).
func (q *Queries) IncrementNotificationAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementNotificationAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications SET status = 'failed' WHERE id = $1
`

// Помечает запись окончательно неуспешной (ретраи исчерпаны, сообщение ушло в DLQ).
func (q *Queries) MarkNotificationFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, id)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications SET status = 'sent', sent_at = now() WHERE id = $1
`

// Идемпотентно: помечает запись доставленной (sent_at — момент успеха). Повторный вызов
// безвреден (sent_at перезапишется тем же смыслом). Воркер зовёт после успешной доставки.
func (q *Queries) MarkNotificationSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}
