// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_allowed_emails.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addAllowedEmail = `-- name: AddAllowedEmail :one
INSERT INTO page_allowed_emails (status_page_id, email) VALUES ($1, $2) RETURNING id, status_page_id, email, created_at
`

type AddAllowedEmailParams struct {
	StatusPageID uuid.UUID
	Email        string
}

func (q *Queries) AddAllowedEmail(ctx context.Context, arg AddAllowedEmailParams) (PageAllowedEmail, error) {
	row := q.db.QueryRow(ctx, addAllowedEmail, arg.StatusPageID, arg.Email)
	var i PageAllowedEmail
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const allowedEmailByID = `-- name: AllowedEmailByID :one
SELECT id, status_page_id, email, created_at FROM page_allowed_emails WHERE id = $1
`

func (q *Queries) AllowedEmailByID(ctx context.Context, id uuid.UUID) (PageAllowedEmail, error) {
	row := q.db.QueryRow(ctx, allowedEmailByID, id)
	var i PageAllowedEmail
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllowedEmail = `-- name: DeleteAllowedEmail :exec
DELETE FROM page_allowed_emails WHERE id = $1
`

func (q *Queries) DeleteAllowedEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllowedEmail, id)
	return err
}

const isEmailAllowed = `-- name: IsEmailAllowed :one
SELECT EXISTS (
    SELECT 1 FROM page_allowed_emails
    WHERE status_page_id = $1 AND lower(email) = lower($2)
)
`

type IsEmailAllowedParams struct {
	StatusPageID uuid.UUID
	Lower        string
}

func (q *Queries) IsEmailAllowed(ctx context.Context, arg IsEmailAllowedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailAllowed, arg.StatusPageID, arg.Lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllowedEmails = `-- name: ListAllowedEmails :many
SELECT id, status_page_id, email, created_at FROM page_allowed_emails WHERE status_page_id = $1 ORDER BY created_at
`

func (q *Queries) ListAllowedEmails(ctx context.Context, statusPageID uuid.UUID) ([]PageAllowedEmail, error) {
	rows, err := q.db.Query(ctx, listAllowedEmails, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageAllowedEmail{}
	for rows.Next() {
		var i PageAllowedEmail
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
