// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_pages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStatusPage = `-- name: CreateStatusPage :one
INSERT INTO status_pages (account_id, name, description, slug, timezone, default_locale, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at
`

type CreateStatusPageParams struct {
	AccountID     uuid.UUID
	Name          string
	Description   string
	Slug          string
	Timezone      string
	DefaultLocale string
	Visibility    string
}

func (q *Queries) CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, createStatusPage,
		arg.AccountID,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.Timezone,
		arg.DefaultLocale,
		arg.Visibility,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Timezone,
		&i.DefaultLocale,
		&i.Visibility,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Theme,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.HidePoweredBy,
		&i.SmtpConfig,
		&i.FromEmail,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStatusPageByID = `-- name: GetStatusPageByID :one
SELECT id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at FROM status_pages WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStatusPageByID(ctx context.Context, id uuid.UUID) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageByID, id)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Timezone,
		&i.DefaultLocale,
		&i.Visibility,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Theme,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.HidePoweredBy,
		&i.SmtpConfig,
		&i.FromEmail,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStatusPageBySlug = `-- name: GetStatusPageBySlug :one
SELECT id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at FROM status_pages WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Timezone,
		&i.DefaultLocale,
		&i.Visibility,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Theme,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.HidePoweredBy,
		&i.SmtpConfig,
		&i.FromEmail,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listStatusPagesByAccount = `-- name: ListStatusPagesByAccount :many
SELECT id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at FROM status_pages
WHERE account_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListStatusPagesByAccount(ctx context.Context, accountID uuid.UUID) ([]StatusPage, error) {
	rows, err := q.db.Query(ctx, listStatusPagesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPage{}
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.Timezone,
			&i.DefaultLocale,
			&i.Visibility,
			&i.PasswordHash,
			&i.CustomDomain,
			&i.DomainVerified,
			&i.Theme,
			&i.LogoUrl,
			&i.FaviconUrl,
			&i.HidePoweredBy,
			&i.SmtpConfig,
			&i.FromEmail,
			&i.RedirectUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStatusPagePassword = `-- name: SetStatusPagePassword :exec
UPDATE status_pages SET password_hash = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetStatusPagePasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

// Задаёт/снимает пароль приватной страницы (этап 4.2). NULL снимает пароль.
// Хранится только хэш (§9). UpdateStatusPage намеренно password_hash не трогает.
func (q *Queries) SetStatusPagePassword(ctx context.Context, arg SetStatusPagePasswordParams) error {
	_, err := q.db.Exec(ctx, setStatusPagePassword, arg.ID, arg.PasswordHash)
	return err
}

const softDeleteStatusPage = `-- name: SoftDeleteStatusPage :exec
UPDATE status_pages SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteStatusPage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStatusPage, id)
	return err
}

const updateStatusPage = `-- name: UpdateStatusPage :one
UPDATE status_pages SET
    name = $2,
    description = $3,
    timezone = $4,
    default_locale = $5,
    visibility = $6,
    theme = $7,
    logo_url = $8,
    favicon_url = $9,
    hide_powered_by = $10,
    redirect_url = $11
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at
`

type UpdateStatusPageParams struct {
	ID            uuid.UUID
	Name          string
	Description   string
	Timezone      string
	DefaultLocale string
	Visibility    string
	Theme         []byte
	LogoUrl       *string
	FaviconUrl    *string
	HidePoweredBy bool
	RedirectUrl   *string
}

func (q *Queries) UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, updateStatusPage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Timezone,
		arg.DefaultLocale,
		arg.Visibility,
		arg.Theme,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.HidePoweredBy,
		arg.RedirectUrl,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Timezone,
		&i.DefaultLocale,
		&i.Visibility,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Theme,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.HidePoweredBy,
		&i.SmtpConfig,
		&i.FromEmail,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
