// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_pages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStatusPage = `-- name: CreateStatusPage :one
INSERT INTO status_pages (account_id, name, description, slug, timezone, default_locale, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at, dokploy_domain_id
`

type CreateStatusPageParams struct {
	AccountID     uuid.UUID
	Name          string
	Description   string
	Slug          string
	Timezone      string
	DefaultLocale string
	Visibility    string
}

func (q *Queries) CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, createStatusPage,
		arg.AccountID,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.Timezone,
		arg.DefaultLocale,
		arg.Visibility,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Timezone,
		&i.DefaultLocale,
		&i.Visibility,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Theme,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.HidePoweredBy,
		&i.SmtpConfig,
		&i.FromEmail,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DokployDomainID,
	)
	return i, err
}

const getStatusPageByID = `-- name: GetStatusPageByID :one
SELECT id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at, dokploy_domain_id FROM status_pages WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStatusPageByID(ctx context.Context, id uuid.UUID) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageByID, id)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Timezone,
		&i.DefaultLocale,
		&i.Visibility,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Theme,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.HidePoweredBy,
		&i.SmtpConfig,
		&i.FromEmail,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DokployDomainID,
	)
	return i, err
}

const getStatusPageBySlug = `-- name: GetStatusPageBySlug :one
SELECT id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at, dokploy_domain_id FROM status_pages WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Timezone,
		&i.DefaultLocale,
		&i.Visibility,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Theme,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.HidePoweredBy,
		&i.SmtpConfig,
		&i.FromEmail,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DokployDomainID,
	)
	return i, err
}

const listStatusPagesByAccount = `-- name: ListStatusPagesByAccount :many
SELECT id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at, dokploy_domain_id FROM status_pages
WHERE account_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListStatusPagesByAccount(ctx context.Context, accountID uuid.UUID) ([]StatusPage, error) {
	rows, err := q.db.Query(ctx, listStatusPagesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPage{}
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.Timezone,
			&i.DefaultLocale,
			&i.Visibility,
			&i.PasswordHash,
			&i.CustomDomain,
			&i.DomainVerified,
			&i.Theme,
			&i.LogoUrl,
			&i.FaviconUrl,
			&i.HidePoweredBy,
			&i.SmtpConfig,
			&i.FromEmail,
			&i.RedirectUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DokployDomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomDomain = `-- name: SetCustomDomain :exec
UPDATE status_pages SET custom_domain = $2, domain_verified = false, dokploy_domain_id = NULL
WHERE id = $1 AND deleted_at IS NULL
`

type SetCustomDomainParams struct {
	ID           uuid.UUID
	CustomDomain *string
}

// Задаёт/снимает собственный домен страницы (этап 4.3) и сбрасывает флаг верификации (домен
// нужно проверить заново) и dokploy_domain_id (старая привязка в Dokploy больше не актуальна —
// отвязывается вызывающим кодом ДО этого запроса). NULL снимает домен. Уникальность — индексом.
func (q *Queries) SetCustomDomain(ctx context.Context, arg SetCustomDomainParams) error {
	_, err := q.db.Exec(ctx, setCustomDomain, arg.ID, arg.CustomDomain)
	return err
}

const setDokployDomainID = `-- name: SetDokployDomainID :exec
UPDATE status_pages SET dokploy_domain_id = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetDokployDomainIDParams struct {
	ID              uuid.UUID
	DokployDomainID *string
}

// Фиксирует ID домена, созданного в Dokploy (domain.create) для custom_domain страницы —
// нужен, чтобы позже удалить его через domain.delete при смене/снятии домена.
func (q *Queries) SetDokployDomainID(ctx context.Context, arg SetDokployDomainIDParams) error {
	_, err := q.db.Exec(ctx, setDokployDomainID, arg.ID, arg.DokployDomainID)
	return err
}

const setDomainVerified = `-- name: SetDomainVerified :exec
UPDATE status_pages SET domain_verified = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetDomainVerifiedParams struct {
	ID             uuid.UUID
	DomainVerified bool
}

// Отмечает результат проверки CNAME (этап 4.3).
func (q *Queries) SetDomainVerified(ctx context.Context, arg SetDomainVerifiedParams) error {
	_, err := q.db.Exec(ctx, setDomainVerified, arg.ID, arg.DomainVerified)
	return err
}

const setStatusPagePassword = `-- name: SetStatusPagePassword :exec
UPDATE status_pages SET password_hash = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetStatusPagePasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

// Задаёт/снимает пароль приватной страницы (этап 4.2). NULL снимает пароль.
// Хранится только хэш (§9). UpdateStatusPage намеренно password_hash не трогает.
func (q *Queries) SetStatusPagePassword(ctx context.Context, arg SetStatusPagePasswordParams) error {
	_, err := q.db.Exec(ctx, setStatusPagePassword, arg.ID, arg.PasswordHash)
	return err
}

const setStatusPageSMTP = `-- name: SetStatusPageSMTP :exec
UPDATE status_pages SET smtp_config = $2, from_email = $3 WHERE id = $1 AND deleted_at IS NULL
`

type SetStatusPageSMTPParams struct {
	ID         uuid.UUID
	SmtpConfig []byte
	FromEmail  *string
}

// Задаёт/снимает кастомный SMTP и адрес отправителя страницы (этап 4.5). NULL — снять.
func (q *Queries) SetStatusPageSMTP(ctx context.Context, arg SetStatusPageSMTPParams) error {
	_, err := q.db.Exec(ctx, setStatusPageSMTP, arg.ID, arg.SmtpConfig, arg.FromEmail)
	return err
}

const softDeleteStatusPage = `-- name: SoftDeleteStatusPage :exec
UPDATE status_pages SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteStatusPage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStatusPage, id)
	return err
}

const updateStatusPage = `-- name: UpdateStatusPage :one
UPDATE status_pages SET
    name = $2,
    description = $3,
    timezone = $4,
    default_locale = $5,
    visibility = $6,
    theme = $7,
    logo_url = $8,
    favicon_url = $9,
    hide_powered_by = $10,
    redirect_url = $11
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, account_id, name, description, slug, timezone, default_locale, visibility, password_hash, custom_domain, domain_verified, theme, logo_url, favicon_url, hide_powered_by, smtp_config, from_email, redirect_url, created_at, updated_at, deleted_at, dokploy_domain_id
`

type UpdateStatusPageParams struct {
	ID            uuid.UUID
	Name          string
	Description   string
	Timezone      string
	DefaultLocale string
	Visibility    string
	Theme         []byte
	LogoUrl       *string
	FaviconUrl    *string
	HidePoweredBy bool
	RedirectUrl   *string
}

func (q *Queries) UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, updateStatusPage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Timezone,
		arg.DefaultLocale,
		arg.Visibility,
		arg.Theme,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.HidePoweredBy,
		arg.RedirectUrl,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Timezone,
		&i.DefaultLocale,
		&i.Visibility,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Theme,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.HidePoweredBy,
		&i.SmtpConfig,
		&i.FromEmail,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DokployDomainID,
	)
	return i, err
}
