// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscribers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const confirmSubscriber = `-- name: ConfirmSubscriber :exec
UPDATE subscribers SET confirmed = true, confirm_token = NULL WHERE id = $1
`

// Подтверждение подписки: confirmed=true, confirm-токен гасится (одноразовый).
func (q *Queries) ConfirmSubscriber(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmSubscriber, id)
	return err
}

const createSubscriber = `-- name: CreateSubscriber :one

INSERT INTO subscribers (
    status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at
`

type CreateSubscriberParams struct {
	StatusPageID     uuid.UUID
	Channel          string
	Address          string
	Confirmed        bool
	ConfirmToken     *string
	UnsubscribeToken *string
	Scope            string
	ComponentIds     []uuid.UUID
}

// ── subscribers ──
func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, createSubscriber,
		arg.StatusPageID,
		arg.Channel,
		arg.Address,
		arg.Confirmed,
		arg.ConfirmToken,
		arg.UnsubscribeToken,
		arg.Scope,
		arg.ComponentIds,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Channel,
		&i.Address,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.Scope,
		&i.ComponentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM subscribers WHERE id = $1
`

// Отписка — физическое удаление строки (в модели §5 у Subscriber нет soft-delete).
func (q *Queries) DeleteSubscriber(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriber, id)
	return err
}

const getSubscriberByConfirmToken = `-- name: GetSubscriberByConfirmToken :one
SELECT id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at FROM subscribers WHERE confirm_token = $1
`

// Поиск по хэшу confirm-токена (double opt-in подтверждение).
func (q *Queries) GetSubscriberByConfirmToken(ctx context.Context, confirmToken *string) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByConfirmToken, confirmToken)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Channel,
		&i.Address,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.Scope,
		&i.ComponentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at FROM subscribers WHERE id = $1
`

func (q *Queries) GetSubscriberByID(ctx context.Context, id uuid.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByID, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Channel,
		&i.Address,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.Scope,
		&i.ComponentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByPageChannelAddress = `-- name: GetSubscriberByPageChannelAddress :one
SELECT id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at FROM subscribers
WHERE status_page_id = $1 AND channel = $2 AND address = $3
`

type GetSubscriberByPageChannelAddressParams struct {
	StatusPageID uuid.UUID
	Channel      string
	Address      string
}

func (q *Queries) GetSubscriberByPageChannelAddress(ctx context.Context, arg GetSubscriberByPageChannelAddressParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByPageChannelAddress, arg.StatusPageID, arg.Channel, arg.Address)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Channel,
		&i.Address,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.Scope,
		&i.ComponentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfirmedSubscribers = `-- name: ListConfirmedSubscribers :many
SELECT id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at FROM subscribers
WHERE status_page_id = $1 AND confirmed = true
ORDER BY created_at
`

// Подтверждённые подписчики страницы — кандидаты на рассылку (движок уведомлений, §8.1).
// Фильтрация по scope/компонентам выполняется в Go (Subscriber.WantsEvent).
func (q *Queries) ListConfirmedSubscribers(ctx context.Context, statusPageID uuid.UUID) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listConfirmedSubscribers, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Channel,
			&i.Address,
			&i.Confirmed,
			&i.ConfirmToken,
			&i.UnsubscribeToken,
			&i.Scope,
			&i.ComponentIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribersByChannelAddress = `-- name: ListSubscribersByChannelAddress :many
SELECT id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at FROM subscribers
WHERE channel = $1 AND address = $2
ORDER BY created_at
`

type ListSubscribersByChannelAddressParams struct {
	Channel string
	Address string
}

// Все подписки одного адреса в канале (один chat_id в Telegram/MAX может быть подписан на
// несколько страниц). Используется ботом для команды /stop без аргумента (отписка отовсюду).
func (q *Queries) ListSubscribersByChannelAddress(ctx context.Context, arg ListSubscribersByChannelAddressParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribersByChannelAddress, arg.Channel, arg.Address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Channel,
			&i.Address,
			&i.Confirmed,
			&i.ConfirmToken,
			&i.UnsubscribeToken,
			&i.Scope,
			&i.ComponentIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubscriberConfirmToken = `-- name: SetSubscriberConfirmToken :one
UPDATE subscribers SET confirm_token = $2, scope = $3, component_ids = $4
WHERE id = $1
RETURNING id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at
`

type SetSubscriberConfirmTokenParams struct {
	ID           uuid.UUID
	ConfirmToken *string
	Scope        string
	ComponentIds []uuid.UUID
}

// Перевыпуск confirm-токена и обновление scope при повторной (неподтверждённой) подписке.
func (q *Queries) SetSubscriberConfirmToken(ctx context.Context, arg SetSubscriberConfirmTokenParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, setSubscriberConfirmToken,
		arg.ID,
		arg.ConfirmToken,
		arg.Scope,
		arg.ComponentIds,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Channel,
		&i.Address,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.Scope,
		&i.ComponentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
