// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscribers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSubscriber = `-- name: CreateSubscriber :one

INSERT INTO subscribers (
    status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at
`

type CreateSubscriberParams struct {
	StatusPageID     uuid.UUID
	Channel          string
	Address          string
	Confirmed        bool
	ConfirmToken     *string
	UnsubscribeToken *string
	Scope            string
	ComponentIds     []uuid.UUID
}

// ── subscribers ──
func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, createSubscriber,
		arg.StatusPageID,
		arg.Channel,
		arg.Address,
		arg.Confirmed,
		arg.ConfirmToken,
		arg.UnsubscribeToken,
		arg.Scope,
		arg.ComponentIds,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Channel,
		&i.Address,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.Scope,
		&i.ComponentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at FROM subscribers WHERE id = $1
`

func (q *Queries) GetSubscriberByID(ctx context.Context, id uuid.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByID, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Channel,
		&i.Address,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.Scope,
		&i.ComponentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfirmedSubscribers = `-- name: ListConfirmedSubscribers :many
SELECT id, status_page_id, channel, address, confirmed, confirm_token, unsubscribe_token, scope, component_ids, created_at, updated_at FROM subscribers
WHERE status_page_id = $1 AND confirmed = true
ORDER BY created_at
`

// Подтверждённые подписчики страницы — кандидаты на рассылку (движок уведомлений, §8.1).
// Фильтрация по scope/компонентам выполняется в Go (Subscriber.WantsEvent).
func (q *Queries) ListConfirmedSubscribers(ctx context.Context, statusPageID uuid.UUID) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listConfirmedSubscribers, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Channel,
			&i.Address,
			&i.Confirmed,
			&i.ConfirmToken,
			&i.UnsubscribeToken,
			&i.Scope,
			&i.ComponentIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
