// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_integrations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWebhookIntegration = `-- name: CreateWebhookIntegration :one
INSERT INTO webhook_integrations (status_page_id, source, name, secret, component_mapping)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status_page_id, source, name, secret, component_mapping, created_at, updated_at
`

type CreateWebhookIntegrationParams struct {
	StatusPageID     uuid.UUID
	Source           string
	Name             string
	Secret           string
	ComponentMapping []byte
}

func (q *Queries) CreateWebhookIntegration(ctx context.Context, arg CreateWebhookIntegrationParams) (WebhookIntegration, error) {
	row := q.db.QueryRow(ctx, createWebhookIntegration,
		arg.StatusPageID,
		arg.Source,
		arg.Name,
		arg.Secret,
		arg.ComponentMapping,
	)
	var i WebhookIntegration
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Source,
		&i.Name,
		&i.Secret,
		&i.ComponentMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookIntegration = `-- name: DeleteWebhookIntegration :exec
DELETE FROM webhook_integrations WHERE id = $1
`

func (q *Queries) DeleteWebhookIntegration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhookIntegration, id)
	return err
}

const getWebhookIntegration = `-- name: GetWebhookIntegration :one
SELECT id, status_page_id, source, name, secret, component_mapping, created_at, updated_at FROM webhook_integrations WHERE id = $1
`

func (q *Queries) GetWebhookIntegration(ctx context.Context, id uuid.UUID) (WebhookIntegration, error) {
	row := q.db.QueryRow(ctx, getWebhookIntegration, id)
	var i WebhookIntegration
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Source,
		&i.Name,
		&i.Secret,
		&i.ComponentMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookIntegrationsByPage = `-- name: ListWebhookIntegrationsByPage :many
SELECT id, status_page_id, source, name, secret, component_mapping, created_at, updated_at FROM webhook_integrations
WHERE status_page_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookIntegrationsByPage(ctx context.Context, statusPageID uuid.UUID) ([]WebhookIntegration, error) {
	rows, err := q.db.Query(ctx, listWebhookIntegrationsByPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookIntegration{}
	for rows.Next() {
		var i WebhookIntegration
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Source,
			&i.Name,
			&i.Secret,
			&i.ComponentMapping,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookIntegration = `-- name: UpdateWebhookIntegration :one
UPDATE webhook_integrations
SET name = $2, secret = $3, component_mapping = $4
WHERE id = $1
RETURNING id, status_page_id, source, name, secret, component_mapping, created_at, updated_at
`

type UpdateWebhookIntegrationParams struct {
	ID               uuid.UUID
	Name             string
	Secret           string
	ComponentMapping []byte
}

func (q *Queries) UpdateWebhookIntegration(ctx context.Context, arg UpdateWebhookIntegrationParams) (WebhookIntegration, error) {
	row := q.db.QueryRow(ctx, updateWebhookIntegration,
		arg.ID,
		arg.Name,
		arg.Secret,
		arg.ComponentMapping,
	)
	var i WebhookIntegration
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Source,
		&i.Name,
		&i.Secret,
		&i.ComponentMapping,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
